// /api/social/admin — merged router for the admin endpoint group:
//   /api/social/publish    (POST: create + optionally publish)
//   /api/social/posts      (GET/POST: list, trigger, retry, cancel, delete)
//   /api/social/accounts   (GET/POST: list, connect, validate, disconnect)
//   /api/social/status     (GET: connection + platform status)
//   /api/social/scheduler  (GET/POST: cron tick, guarded by SCHEDULER_CRON_SECRET)
// /api/social/<path> is rewritten here by vercel.json, so browser-facing and
// platform-facing URLs stay identical. Merging keeps the project under Vercel's
// Hobby serverless-function cap (12 per deployment).
import { getServiceClient } from '../../shared/social/db.mjs';
import { verifyAdmin } from '../../shared/social/auth.mjs';
import { getAdapter, isPlatform, platformList } from '../../shared/social/registry.mjs';
import { decryptToken } from '../../shared/social/crypto.mjs';
import { triggerPost, runPublish, createPost, dedupeHash, enqueueDueScheduled, requeueRetryable, logPost } from '../../shared/social/publish-engine.mjs';
import { runRule, getGlobalSettings } from '../../shared/social/auto-generator.mjs';
import { json, readBody, corsHeaders } from '../../shared/social/http.mjs';

export const config = { maxDuration: 120 };

const BATCH_LIMIT = 4;

function stripBearer(v) {
  const m = /^Bearer\s+(.+)$/i.exec(String(v || ''));
  return m ? m[1].trim() : String(v || '').trim();
}

function route(req) {
  return String(req.query.__path || '');
}

function clean(account) {
  if (!account) return account;
  const { access_token_enc, refresh_token_enc, ...rest } = account;
  return rest;
}

async function handlePublish(req, res, cors) {
  if (req.method !== 'POST') return json(req, res, { ok: false, error: 'Method not allowed.' }, 405, cors);
  const body = await readBody(req, 20);
  const platform = String(body.platform || '');
  const mode = String(body.mode || 'publish_now');
  if (!isPlatform(platform)) return json(req, res, { ok: false, error: 'Unknown platform.' }, 400, cors);
  if (!['publish_now', 'schedule', 'draft'].includes(mode)) return json(req, res, { ok: false, error: 'mode must be publish_now, schedule or draft.' }, 400, cors);

  const adapter = getAdapter(platform);
  const sb = getServiceClient();

  const ps = await sb.from('social_platform_settings').select('*').eq('platform', platform).maybeSingle();
  if (!ps.data?.enabled) return json(req, res, { ok: false, error: `${adapter.metadata.label} is disabled in Platform Settings.` }, 400, cors);

  const { data: account } = await sb.from('social_accounts')
    .select('*')
    .eq('platform', platform)
    .eq('status', 'connected')
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();

  if (mode !== 'draft' && !account) return json(req, res, { ok: false, error: `No connected ${adapter.metadata.label} account. Connect the account first.` }, 400, cors);
  if (adapter.metadata.usesOAuth && !adapter.oauthAvailable()) {
    return json(req, res, { ok: false, error: `${adapter.metadata.label} API credentials are not configured server-side.` }, 400, cors);
  }

  const caption = String(body.caption || '').trim();
  const media = Array.isArray(body.media) ? body.media.filter((m) => m && m.url) : [];

  const scheduledFor = mode === 'schedule' && body.scheduledFor ? new Date(body.scheduledFor) : null;
  if (mode === 'schedule' && (!scheduledFor || Number.isNaN(scheduledFor.getTime()))) {
    return json(req, res, { ok: false, error: 'A valid scheduledFor date is required for scheduling.' }, 400, cors);
  }

  if (!body.allowDuplicate && (mode === 'publish_now' || mode === 'schedule')) {
    const hash = dedupeHash({ platform, contentType: body.contentType || 'manual', sourceType: body.sourceType, sourceId: body.sourceId, caption });
    const existing = await sb.from('social_posts').select('id').eq('platform', platform).eq('dedupe_hash', hash).maybeSingle();
    if (existing.data) {
      return json(req, res, {
        ok: false,
        error: 'Duplicate: this content already exists for this platform. Enable "Allow duplicate" to post anyway.',
        duplicate: true,
      }, 409, cors);
    }
  }

  const post = await createPost({
    platform,
    platformAccountId: account?.id || null,
    contentType: String(body.contentType || 'manual'),
    sourceType: body.sourceType ? String(body.sourceType) : null,
    sourceId: body.sourceId ? String(body.sourceId) : null,
    caption,
    hashtags: body.hashtags,
    media,
    scheduledFor: mode === 'schedule' ? scheduledFor : null,
    autoGenerated: false,
    metadata: body.metadata || {},
    linkUrl: body.linkUrl,
    maxRetries: Math.max(0, Number(body.maxRetries) || 3),
  });

  if (mode === 'draft') {
    await sb.from('social_posts').update({ status: 'draft', scheduled_for: null }).eq('id', post.id);
    return json(req, res, { ok: true, post, status: 'draft', message: 'Saved as draft.' }, 200, cors);
  }

  if (mode === 'schedule') {
    return json(req, res, { ok: true, post, status: 'scheduled', message: 'Scheduled. The server-side scheduler will publish it automatically.' }, 200, cors);
  }

  const { ok, result } = await runPublish({ post, by: 'manual' });
  const updated = await sb.from('social_posts').select('*').eq('id', post.id).maybeSingle();
  return json(req, res, {
    ok,
    post: updated.data || post,
    status: updated.data?.status || 'published',
    result: result || null,
    message: ok ? 'Published successfully.' : 'Publish reported a failure.',
  }, ok ? 200 : 502, cors);
}

async function handlePosts(req, res, cors) {
  const sb = getServiceClient();

  if (req.method === 'GET') {
    const { platform, status, limit = 100 } = req.query;
    let q = sb.from('social_posts').select('*');
    if (platform) q = q.eq('platform', String(platform));
    if (status) q = q.eq('status', String(status));
    const { data, error } = await q.order('created_at', { ascending: false }).limit(String(limit) === 'all' ? 5000 : Math.min(Number(limit) || 100, 500));
    if (error) return json(req, res, { ok: false, error: error.message }, 400, cors);
    return json(req, res, { ok: true, posts: data || [] }, 200, cors);
  }

  if (req.method === 'POST') {
    const body = await readBody(req);
    const action = body.action || '';
    const id = body.post_id;
    if (!id) return json(req, res, { ok: false, error: 'post_id is required.' }, 400, cors);

    if (action === 'trigger') {
      await triggerPost(String(id));
      const { data } = await sb.from('social_posts').select('*').eq('id', id).maybeSingle();
      return json(req, res, { ok: true, message: 'Publish triggered.', post: data }, 200, cors);
    }

    if (action === 'retry') {
      const { data } = await sb.from('social_posts').select('*').eq('id', id).maybeSingle();
      if (!data) return json(req, res, { ok: false, error: 'Post not found.' }, 404, cors);
      if (data.status !== 'failed') return json(req, res, { ok: false, error: 'Only failed posts can be retried.' }, 400, cors);
      await sb.from('social_posts').update({ status: 'queued', retry_count: 0, next_retry_at: null, error_detail: {} }).eq('id', id);
      await runPublish({ postId: String(id), by: 'manual retry' });
      const after = await sb.from('social_posts').select('*').eq('id', id).maybeSingle();
      return json(req, res, { ok: true, message: 'Retried.', post: after.data }, after.data?.status === 'published' ? 200 : 202, cors);
    }

    if (action === 'cancel') {
      const { data } = await sb.from('social_posts').select('id').eq('id', id).maybeSingle();
      if (!data) return json(req, res, { ok: false, error: 'Post not found.' }, 404, cors);
      await sb.from('social_posts').update({ status: 'cancelled', next_retry_at: null, updated_at: new Date().toISOString() }).eq('id', id);
      return json(req, res, { ok: true, message: 'Post cancelled.' }, 200, cors);
    }

    if (action === 'delete') {
      const { data } = await sb.from('social_posts').select('id').eq('id', id).maybeSingle();
      if (!data) return json(req, res, { ok: false, error: 'Post not found.' }, 404, cors);
      await sb.from('social_posts').delete().eq('id', id);
      return json(req, res, { ok: true, message: 'Post deleted.' }, 200, cors);
    }

    return json(req, res, { ok: false, error: 'Unknown action.' }, 400, cors);
  }

  return json(req, res, { ok: false, error: 'Method not allowed.' }, 405, cors);
}

async function handleAccounts(req, res, cors) {
  const sb = getServiceClient();

  if (req.method === 'GET') {
    const { data, error } = await sb.from('social_accounts').select('*').order('platform', { ascending: true });
    if (error) return json(req, res, { ok: false, error: error.message }, 400, cors);
    return json(req, res, { ok: true, accounts: (data || []).map(clean) }, 200, cors);
  }

  if (req.method === 'POST') {
    const body = await readBody(req);
    const action = body.action || 'connect';

    if (action === 'connect') {
      const adapter = getAdapter(body.platform);
      if (adapter.metadata.usesOAuth) {
        return json(req, res, { ok: false, error: `${adapter.metadata.label} connects through official OAuth (use Connect).` }, 400, cors);
      }
      const settings = await sb.from('social_platform_settings').select('*').eq('platform', body.platform).maybeSingle();
      let conn;
      if (typeof adapter.connectFromSettings === 'function') {
        conn = await adapter.connectFromSettings(settings?.data || null, body);
      } else {
        conn = await adapter.validateConnection(undefined, settings?.data || null);
        conn = { ok: conn.ok, profile: conn.profile || {}, extra: {}, note: conn.note };
      }
      if (!conn.ok) return json(req, res, { ok: false, error: conn.note || 'Connection failed.' }, 400, cors);

      const existing = await sb.from('social_accounts').select('id').eq('platform', body.platform).maybeSingle();
      const payload = {
        platform: body.platform,
        platform_user_id: conn.profile?.platformUserId || null,
        account_name: conn.profile?.displayName || null,
        display_name: conn.profile?.displayName || null,
        avatar_url: conn.profile?.avatarUrl || null,
        status: 'connected',
        scopes: conn.profile?.scopes || [],
        raw_profile: conn.profile || {},
        extra: { ...(conn.extra || {}) },
        last_error: null,
        requires_approval: Boolean(conn.requiresApproval),
        disconnected_at: null,
        updated_at: new Date().toISOString(),
      };
      if (existing?.data?.id) {
        await sb.from('social_accounts').update(payload).eq('id', existing.data.id);
      } else {
        await sb.from('social_accounts').insert(payload).select('id').maybeSingle();
      }
      return json(req, res, { ok: true, message: `${adapter.metadata.label} connected.` }, 200, cors);
    }

    if (action === 'validate') {
      const { data } = await sb.from('social_accounts').select('*').eq('id', body.account_id).maybeSingle();
      if (!data) return json(req, res, { ok: false, error: 'Account not found.' }, 404, cors);
      const adapter = getAdapter(data.platform);
      let result;
      try {
        if (adapter.metadata.usesOAuth && data.access_token_enc) {
          result = await adapter.validateConnection({
            ...clean(data),
            accessToken: decryptToken(data.access_token_enc),
          });
        } else if (typeof adapter.validateConnection === 'function') {
          result = await adapter.validateConnection();
        } else {
          result = { ok: true, note: 'Connection stored.' };
        }
      } catch (err) {
        result = { ok: false, note: err.message };
        await sb.from('social_accounts').update({ last_error: err.message, status: 'error' }).eq('id', data.id);
      }
      return json(req, res, { ok: true, ...result, account: clean(data) }, 200, cors);
    }

    if (action === 'disconnect') {
      const { data } = await sb.from('social_accounts').select('*').eq('id', body.account_id).maybeSingle();
      if (!data) return json(req, res, { ok: false, error: 'Account not found.' }, 404, cors);
      await sb.from('social_accounts').update({
        status: 'disconnected',
        access_token_enc: null,
        refresh_token_enc: null,
        token_expires_at: null,
        refresh_token_expires_at: null,
        disconnected_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      }).eq('id', data.id);
      return json(req, res, { ok: true, message: `${data.platform} disconnected.` }, 200, cors);
    }

    if (action === 'reconnect') {
      const adapter = getAdapter(body.platform);
      if (adapter.metadata.usesOAuth) {
        return json(req, res, { ok: true, redirect: `/api/social/oauth/start?platform=${encodeURIComponent(body.platform)}` }, 200, cors);
      }
      return json(req, res, { ok: true, redirect: null, message: 'Use Connect for this platform.' }, 200, cors);
    }

    return json(req, res, { ok: false, error: 'Unknown action.' }, 400, cors);
  }

  return json(req, res, { ok: false, error: 'Method not allowed.' }, 405, cors);
}

async function handleStatus(req, res, cors) {
  const sb = getServiceClient();

  const [{ data: settings }, { data: accounts }, { data: platformSettings }, { data: postCounts }] = await Promise.all([
    sb.from('social_settings').select('*').eq('id', 1).maybeSingle(),
    sb.from('social_accounts').select('id,platform,status,display_name,account_name,requires_approval,extra,last_error,updated_at').order('platform'),
    sb.from('social_platform_settings').select('*'),
    sb.from('social_posts').select('id,status', { count: 'exact', head: false }),
  ]);

  const myPlatforms = platformList();
  const statusList = myPlatforms.map((p) => {
    const account = (accounts || []).find((a) => a.platform === p.id);
    const ps = (platformSettings || []).find((s) => s.platform === p.id);
    const { access_token_enc, refresh_token_enc, ...safeAccount } = account || {};
    return {
      ...p,
      configured: p.officiallyConfigured,
      connected: account?.status === 'connected',
      accountStatus: account?.status || 'not_connected',
      accountName: account?.display_name || account?.account_name || null,
      account: safeAccount || null,
      requiresApproval: p.requirements?.requiresApproval || account?.requires_approval || ps?.requires_approval || false,
      approvalNote: ps?.approval_note || p.requirements?.note || '',
      enabled: Boolean(ps?.enabled),
      capability: p.capability,
      maxPostsPerDay: ps?.max_posts_per_day ?? 5,
      accountError: account?.last_error || null,
      oauth: p.usesOAuth,
    };
  });

  const counts = (postCounts || []).reduce((acc, p) => { acc[p.status] = (acc[p.status] || 0) + 1; return acc; }, {});
  return json(req, res, {
    ok: true,
    serverConfigured: {
      supabase: Boolean(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY),
      tokenEncryption: Boolean(process.env.SOCIAL_TOKEN_ENC_KEY),
      schedulerSecret: Boolean(process.env.SCHEDULER_CRON_SECRET),
    },
    settings: settings || {},
    platforms: statusList,
    accounts: (accounts || []).map((a) => ({ ...a, access_token_enc: undefined, refresh_token_enc: undefined })),
    counts,
  }, 200, cors);
}

async function handleScheduler(req, res, cors) {
  const authHeader = req.headers['x-cron-secret'] || req.headers.authorization || '';
  const ok = authHeader && stripBearer(authHeader) === (process.env.SCHEDULER_CRON_SECRET || process.env.SOCIAL_INTERNAL_SECRET || '');
  if (!ok) return json(req, res, { ok: false, error: 'Invalid scheduler secret.' }, 403, cors);

  if (req.method !== 'GET' && req.method !== 'POST') return json(req, res, { ok: false, error: 'Method not allowed.' }, 405, cors);

  const payload = {};
  try {
    const sb = getServiceClient();
    const startTime = Date.now();

    const staleWindow = new Date(Date.now() - 10 * 60 * 1000).toISOString();
    const { data: stale } = await sb.from('social_posts').select('*').eq('status', 'publishing').lt('updated_at', staleWindow).limit(20);
    for (const s of stale || []) {
      await sb.from('social_posts').update({ status: 'queued', updated_at: new Date().toISOString() }).eq('id', s.id);
      await logPost(sb, { postId: s.id, platform: s.platform, level: 'warn', message: 'Recovered a stale publishing job into the queue.' });
      payload.recovered = (payload.recovered || 0) + 1;
    }

    const global = await getGlobalSettings(sb);
    if (global.automation_paused) {
      payload.paused = true;
    } else {
      const enqueued = await enqueueDueScheduled(sb);
      payload.scheduledEnqueued = enqueued;
    }

    if (!global.automation_paused) {
      const requeued = await requeueRetryable(sb);
      payload.retriesRequeued = requeued;
    }

    const autoResults = [];
    if (global.auto_posting_enabled && !global.automation_paused) {
      const now = new Date().toISOString();
      const { data: dueRules } = await sb.from('social_automation_rules')
        .select('*')
        .eq('enabled', true)
        .or(`next_run_at.is.null,next_run_at.lte.${now}`)
        .limit(20);
      for (const rule of dueRules || []) {
        try {
          const result = await runRule(rule, { sb, req });
          autoResults.push({ rule: rule.id, ...result });
        } catch (err) {
          autoResults.push({ rule: rule.id, error: err.message });
        }
      }
      payload.rules = autoResults;

      const { data: queued } = await sb.from('social_posts').select('*').eq('status', 'queued').order('created_at', { ascending: true }).limit(BATCH_LIMIT);
      const publishResults = [];
      let published = 0;
      for (const post of queued || []) {
        try {
          await runPublish({ post, by: 'scheduler' });
          published += 1;
          publishResults.push({ post: post.id, ok: true });
        } catch (err) {
          publishResults.push({ post: post.id, ok: false, error: err.message });
        }
        if (Date.now() - startTime > 90 * 1000) break;
      }
      payload.published = published;
      payload.batch = publishResults;
    } else {
      payload.autoPosting = 'disabled';
    }

    payload.durationMs = Date.now() - startTime;
    return json(req, res, { ok: true, ...payload }, 200, cors);
  } catch (err) {
    const status = err.status || 500;
    return json(req, res, { ok: false, error: err.message, ...payload }, status, cors);
  }
}

export default async function handler(req, res) {
  const cors = corsHeaders();
  if (req.method === 'OPTIONS') {
    res.statusCode = 204;
    res.setHeader('Access-Control-Allow-Origin', cors['Access-Control-Allow-Origin']);
    res.setHeader('Access-Control-Allow-Headers', cors['Access-Control-Allow-Headers']);
    res.setHeader('Access-Control-Allow-Methods', cors['Access-Control-Allow-Methods']);
    res.end('');
    return;
  }
  const r = route(req);
  try {
    if (r === '/api/social/publish') return await handlePublish(req, res, cors);
    if (r === '/api/social/posts') return await handlePosts(req, res, cors);
    if (r === '/api/social/accounts') return await handleAccounts(req, res, cors);
    if (r === '/api/social/status') return await handleStatus(req, res, cors);
    if (r === '/api/social/scheduler') return await handleScheduler(req, res, cors);
    return json(req, res, { ok: false, error: 'Unknown endpoint.' }, 404, cors);
  } catch (err) {
    const status = err.status || (err.code === 'DUPLICATE' ? 409 : 500);
    return json(req, res, { ok: false, error: err.message, code: err.code || '' }, status, cors);
  }
}