// Motorhome listings — 20 luxury/beautiful motorhomes, photos from Pexels.
// Each motorhome has its own dedicated set of 6 unique photos
// (2 exteriors + living interior + kitchen + bedroom + bathroom) — no photo is reused.

const PX = (id, w = 1200) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}`;

function buildGallery(ids) {
  return ids.map((id, i) => PX(id, i < 2 ? 1200 : 1000));
}

export const MOTORHOME_LISTINGS = [
  {
    property_id: 'KCO-MH0001', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Winnebago Solis Pocket 36B — New Class B',
    description: 'The 2026 Winnebago Solis Pocket 36B is a brand-new compact Class B motorhome built for two. It pairs an efficient turbo-diesel powertrain with a beautifully finished living area that includes a full kitchenette with two-burner cooktop, sink and 12V compressor fridge, a dinette that converts into a queen bed, and a wet bath with a premium cassette toilet. Features a 30-gallon fresh water tank, 200W solar panel, and Truma Combi heating. Sleeps 2 and seats 4. Stock #MH-0001.',
    price: 139900, currency: 'USD',
    brand: 'Winnebago', model: 'Solis Pocket 36B', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '8-Speed Auto', fuel_type: 'Diesel',
    engine: '2.1L Turbo Diesel I4 (161 HP)',
    drive_type: 'RWD', color: 'Pearl White',
    property_type: 'Class B Motorhome',
    sleeping_capacity: '2', seating_capacity: '4',
    bathroom: 'Wet Bath with Cassette Toilet', kitchen: 'Full Kitchenette with Two-Burner Cooktop', water_tank: '30 gallons',
    vin: 'KCO0001MH0001', stock_number: 'MH-0001',
    listing_status: 'sale',
    images: buildGallery([2580312, 3042332, 16746356, 12329418, 12590448, 358592]),
    rating: 4.8, rating_count: 34, favorite_count: 21,
    features: ['Turbo Diesel', 'Queen Convertible Bed', '200W Solar', 'Truma Combi Heat', '12V Compressor Fridge', 'Cassette Toilet', 'Sleeps 2', '30 Gal Water'],
  },
  {
    property_id: 'KCO-MH0002', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2025 Winnebago Revel 44A — New 4x4 Class B',
    description: 'The 2025 Winnebago Revel 44A is a brand-new go-anywhere Class B 4x4 motorhome on the Mercedes-Benz Sprinter chassis. It delivers confident all-wheel-drive power with a 3.0L turbo diesel V6, plus a premium interior with a rear garage with full bathroom, a drop-down galley, and a convertible bed. Includes a 200W solar system, 2,000W inverter, and Truma Combi heat. Sleeps 2 comfortably. Stock #MH-0002.',
    price: 189900, currency: 'USD',
    brand: 'Winnebago', model: 'Revel 44A', model_year: 2025,
    condition: 'New', mileage: '0 mi',
    transmission: '7-Speed Auto', fuel_type: 'Diesel',
    engine: '3.0L Turbo Diesel V6 (188 HP)',
    drive_type: '4WD', color: 'Silver Gray',
    property_type: 'Class B Motorhome',
    sleeping_capacity: '2', seating_capacity: '4',
    bathroom: 'Full Bathroom with Cassette Toilet', kitchen: 'Drop-Down Galley with Induction Cooktop', water_tank: '24 gallons',
    vin: 'KCO0002MH0002', stock_number: 'MH-0002',
    listing_status: 'sale',
    images: buildGallery([7990947, 28273511, 7163683, 8266853, 13650229, 19846354]),
    rating: 4.9, rating_count: 29, favorite_count: 24,
    features: ['Mercedes 4x4 Chassis', '3.0L Turbo Diesel', '200W Solar', '2,000W Inverter', 'Rear Garage', 'Full Bath', 'Truma Combi Heat', 'Sleeps 2'],
  },
  {
    property_id: 'KCO-MH0003', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Winnebago View 24D — New Class C',
    description: 'The 2026 Winnebago View 24D is a brand-new diesel Class C motorhome on the Mercedes-Benz Sprinter 3500 chassis. Powered by a 3.0L turbo diesel V6, it offers a slide-out dinette, rear queen bed, full bath with shower, and a fully equipped kitchen with three-burner cooktop, 10.7-cu-ft refrigerator, and microwave. Includes a 215W solar panel and 30-gallon fresh water tank. Sleeps 4 and seats 6. Stock #MH-0003.',
    price: 164500, currency: 'USD',
    brand: 'Winnebago', model: 'View 24D', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '7-Speed Auto', fuel_type: 'Diesel',
    engine: '3.0L Turbo Diesel V6 (188 HP)',
    drive_type: 'RWD', color: 'Summit White',
    property_type: 'Class C Motorhome',
    sleeping_capacity: '4', seating_capacity: '6',
    bathroom: 'Full Bath with Shower', kitchen: 'Kitchen with Three-Burner Cooktop and 10.7-cu-ft Fridge', water_tank: '30 gallons',
    vin: 'KCO0003MH0003', stock_number: 'MH-0003',
    listing_status: 'sale',
    images: buildGallery([6726698, 17910092, 10630987, 21287221, 19001462, 19866402]),
    rating: 4.7, rating_count: 41, favorite_count: 19,
    features: ['Mercedes Diesel Chassis', 'Slide-Out Dinette', 'Rear Queen Bed', '215W Solar', 'Full Bath', 'Sleeps 4', '30 Gal Water'],
  },
  {
    property_id: 'KCO-MH0004', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2025 Thor Venetian A40 — New Class A',
    description: 'The 2025 Thor Motor Coach Venetian A40 is a brand-new luxury Class A diesel motorhome built on a Freightliner XCR raised-rail chassis. Powered by a Cummins 6.7L turbo diesel, it features a full-wall slide with a residential kitchen, king-size bed in a master suite, full bath with glass shower, and a mid-bath. Includes a 10kW Onan diesel generator, 800W solar system, and 100-gallon fresh water tank. Sleeps 6 and seats 7. Stock #MH-0004.',
    price: 429900, currency: 'USD',
    brand: 'Thor Motor Coach', model: 'Venetian A40', model_year: 2025,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Diesel',
    engine: 'Cummins 6.7L Turbo Diesel (360 HP)',
    drive_type: 'RWD', color: 'Champagne',
    property_type: 'Class A Motorhome',
    sleeping_capacity: '6', seating_capacity: '7',
    bathroom: 'Full Bath with Glass Shower', kitchen: 'Residential Kitchen with Full-Size Fridge', water_tank: '100 gallons',
    vin: 'KCO0004MH0004', stock_number: 'MH-0004',
    listing_status: 'sale',
    images: buildGallery([36844834, 37443372, 23345927, 28057656, 7476226, 7534166]),
    rating: 4.9, rating_count: 26, favorite_count: 22,
    features: ['Full-Wall Slide', 'Cummins 6.7L Diesel', 'Residential Kitchen', 'King Bed', '10kW Generator', '800W Solar', 'Sleeps 6', '100 Gal Water'],
  },
  {
    property_id: 'KCO-MH0005', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Thor Chateau 31W — New Class C',
    description: 'The 2026 Thor Motor Coach Chateau 31W is a brand-new family Class C motorhome on a Ford E-450 chassis. Powered by a 7.3L V8 gasoline engine, it offers a cab-over bunk, slide-out sofa, rear queen bed, full bath with shower, and a well-appointed kitchen with three-burner cooktop, refrigerator, and microwave. Includes a 4kW Onan gas generator and 55-gallon fresh water tank. Sleeps 6 and seats 8. Stock #MH-0005.',
    price: 129900, currency: 'USD',
    brand: 'Thor Motor Coach', model: 'Chateau 31W', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Gasoline',
    engine: '7.3L V8 (350 HP)',
    drive_type: 'RWD', color: 'White with Graphite Accents',
    property_type: 'Class C Motorhome',
    sleeping_capacity: '6', seating_capacity: '8',
    bathroom: 'Full Bath with Shower', kitchen: 'Kitchen with Three-Burner Cooktop and Fridge', water_tank: '55 gallons',
    vin: 'KCO0005MH0005', stock_number: 'MH-0005',
    listing_status: 'sale',
    images: buildGallery([13601011, 30131061, 33816353, 37032237, 8154301, 6970058]),
    rating: 4.6, rating_count: 48, favorite_count: 26,
    features: ['Cab-Over Bunk', '7.3L V8 Gas', 'Slide-Out Sofa', '4kW Generator', 'Sleeps 6', 'Rear Queen Bed', '55 Gal Water'],
  },
  {
    property_id: 'KCO-MH0006', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2025 Airstream Atlas — New Class B',
    description: 'The 2025 Airstream Atlas is a brand-new premium Class B motorhome built on the Mercedes-Benz Sprinter 2500 4WD chassis. Powered by a 3.0L turbo diesel V6, the interior features a power retractable sofa bed, a wet bath with cassette toilet, and a galley kitchen with 12V compressor fridge and induction cooktop. Includes a 200W solar panel and 20-gallon fresh water tank. Sleeps 2 and seats 2. Stock #MH-0006.',
    price: 174900, currency: 'USD',
    brand: 'Airstream', model: 'Atlas', model_year: 2025,
    condition: 'New', mileage: '0 mi',
    transmission: '7-Speed Auto', fuel_type: 'Diesel',
    engine: '3.0L Turbo Diesel V6 (211 HP)',
    drive_type: '4WD', color: 'Airstream Silver',
    property_type: 'Class B Motorhome',
    sleeping_capacity: '2', seating_capacity: '2',
    bathroom: 'Wet Bath with Cassette Toilet', kitchen: 'Galley with 12V Fridge and Induction Cooktop', water_tank: '20 gallons',
    vin: 'KCO0006MH0006', stock_number: 'MH-0006',
    listing_status: 'sale',
    images: buildGallery([2962089, 3560366, 7163686, 12513483, 7476225, 29252363]),
    rating: 4.8, rating_count: 37, favorite_count: 28,
    features: ['Mercedes Sprinter 4WD', 'Power Retractable Sofa Bed', '200W Solar', 'Induction Cooktop', 'Cassette Toilet', 'Sleeps 2'],
  },
  {
    property_id: 'KCO-MH0007', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Airstream Interstate 19X — New Class B',
    description: 'The 2026 Airstream Interstate 19X is a brand-new luxury Class B motorhome on the Mercedes-Benz Sprinter 2500 4WD chassis. Powered by a 3.0L turbo diesel V6, it offers a rear lounge that converts to a twin bed, a wet bath with cassette toilet, and a galley with induction cooktop and 12V fridge. Includes a 200W solar system and Truma Combi heat. Sleeps 2 and seats 4. Stock #MH-0007.',
    price: 199900, currency: 'USD',
    brand: 'Airstream', model: 'Interstate 19X', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '7-Speed Auto', fuel_type: 'Diesel',
    engine: '3.0L Turbo Diesel V6 (211 HP)',
    drive_type: '4WD', color: 'Ivory White',
    property_type: 'Class B Motorhome',
    sleeping_capacity: '2', seating_capacity: '4',
    bathroom: 'Wet Bath with Cassette Toilet', kitchen: 'Galley with Induction Cooktop and 12V Fridge', water_tank: '20 gallons',
    vin: 'KCO0007MH0007', stock_number: 'MH-0007',
    listing_status: 'sale',
    images: buildGallery([20396250, 15781024, 9354548, 6510427, 19478842, 33054908]),
    rating: 4.9, rating_count: 22, favorite_count: 18,
    features: ['Mercedes 4x4 Chassis', 'Induction Cooktop', '200W Solar', 'Truma Combi Heat', 'Cassette Toilet', 'Sleeps 2'],
  },
  {
    property_id: 'KCO-MH0008', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Forest River Sunseeker 2860DS — New Class C',
    description: 'The 2026 Forest River Sunseeker 2860DS is a brand-new family Class C motorhome on a Ford E-450 chassis. Powered by a 7.3L V8 gasoline engine, it features a slide-out with sofa, overhead cab bunk, rear double bed, full bath with shower, and a kitchen with three-burner cooktop, oven, and refrigerator. Includes a 4kW generator and 50-gallon fresh water tank. Sleeps 8 and seats 8. Stock #MH-0008.',
    price: 119900, currency: 'USD',
    brand: 'Forest River', model: 'Sunseeker 2860DS', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Gasoline',
    engine: '7.3L V8 (350 HP)',
    drive_type: 'RWD', color: 'White with Blue Accents',
    property_type: 'Class C Motorhome',
    sleeping_capacity: '8', seating_capacity: '8',
    bathroom: 'Full Bath with Shower', kitchen: 'Kitchen with Three-Burner Cooktop, Oven and Fridge', water_tank: '50 gallons',
    vin: 'KCO0008MH0008', stock_number: 'MH-0008',
    listing_status: 'sale',
    images: buildGallery([26649027, 28896646, 8866156, 5378403, 8968396, 19866441]),
    rating: 4.5, rating_count: 56, favorite_count: 30,
    features: ['Slide-Out Sofa', 'Cab Bunk', '7.3L V8', '4kW Generator', 'Oven', 'Sleeps 8', '50 Gal Water'],
  },
  {
    property_id: 'KCO-MH0009', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2025 Forest River Forester 3011DS — New Class C',
    description: 'The 2025 Forest River Forester 3011DS is a brand-new upscale Class C motorhome on a Ford E-450 chassis. Powered by a 7.3L V8 gasoline engine, it offers a slide-out dinette, cab-over bunk, rear queen bed, full bath with shower, and a chef-style kitchen with three-burner cooktop and oven. Includes a 4kW generator, 300W solar panel, and 50-gallon fresh water tank. Sleeps 7 and seats 8. Stock #MH-0009.',
    price: 139900, currency: 'USD',
    brand: 'Forest River', model: 'Forester 3011DS', model_year: 2025,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Gasoline',
    engine: '7.3L V8 (350 HP)',
    drive_type: 'RWD', color: 'Ice White',
    property_type: 'Class C Motorhome',
    sleeping_capacity: '7', seating_capacity: '8',
    bathroom: 'Full Bath with Shower', kitchen: 'Chef Kitchen with Three-Burner Cooktop and Oven', water_tank: '50 gallons',
    vin: 'KCO0009MH0009', stock_number: 'MH-0009',
    listing_status: 'sale',
    images: buildGallery([6170835, 6170833, 10892833, 4906250, 8866132, 19866415]),
    rating: 4.7, rating_count: 45, favorite_count: 27,
    features: ['Slide-Out Dinette', '7.3L V8', '300W Solar', '4kW Generator', 'Sleeps 7', 'Rear Queen Bed'],
  },
  {
    property_id: 'KCO-MH0010', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Coachmen Encore 40TS — New Class A',
    description: 'The 2026 Coachmen Encore 40TS is a brand-new luxury Class A diesel motorhome on a Freightliner XCM chassis. Powered by a Cummins 8.9L turbo diesel, it features a full-wall slide with a residential kitchen, king bed master suite, full bath with glass shower, and a rear lounge. Includes a 12kW Onan generator, 800W solar system, and 100-gallon fresh water tank. Sleeps 5 and seats 6. Stock #MH-0010.',
    price: 459900, currency: 'USD',
    brand: 'Coachmen', model: 'Encore 40TS', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Diesel',
    engine: 'Cummins 8.9L Turbo Diesel (380 HP)',
    drive_type: 'RWD', color: 'Warm Gray',
    property_type: 'Class A Motorhome',
    sleeping_capacity: '5', seating_capacity: '6',
    bathroom: 'Full Bath with Glass Shower', kitchen: 'Residential Kitchen with Full-Size Fridge', water_tank: '100 gallons',
    vin: 'KCO0010MH0010', stock_number: 'MH-0010',
    listing_status: 'sale',
    images: buildGallery([20817312, 12441114, 18029603, 6945998, 15240841, 19899059]),
    rating: 4.9, rating_count: 24, favorite_count: 20,
    features: ['Full-Wall Slide', 'Cummins 8.9L Diesel', 'Residential Kitchen', 'King Bed', '12kW Generator', '800W Solar', '100 Gal Water'],
  },
  {
    property_id: 'KCO-MH0011', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Entegra Reatta 30A — New Class A',
    description: 'The 2026 Entegra Coach Reatta 30A is a brand-new luxury Class A motorhome on a Freightliner XCM chassis. Powered by a Cummins 8.9L turbo diesel, it features a large slide-out living area, residential kitchen, king bed master suite, and a full bath with ceramic tile shower. Includes a 10kW Onan generator and 90-gallon fresh water tank. Sleeps 4 and seats 6. Stock #MH-0011.',
    price: 489900, currency: 'USD',
    brand: 'Entegra Coach', model: 'Reatta 30A', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Diesel',
    engine: 'Cummins 8.9L Turbo Diesel (380 HP)',
    drive_type: 'RWD', color: 'Canyon Stone',
    property_type: 'Class A Motorhome',
    sleeping_capacity: '4', seating_capacity: '6',
    bathroom: 'Full Bath with Tile Shower', kitchen: 'Residential Kitchen with Induction Range', water_tank: '90 gallons',
    vin: 'KCO0011MH0011', stock_number: 'MH-0011',
    listing_status: 'sale',
    images: buildGallery([18628431, 21935169, 33816355, 12329021, 15883917, 7587301]),
    rating: 4.8, rating_count: 31, favorite_count: 17,
    features: ['Slide-Out Living Area', 'Cummins 8.9L Diesel', 'Residential Kitchen', 'King Bed', '10kW Generator', 'Tile Shower'],
  },
  {
    property_id: 'KCO-MH0012', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2025 Entegra Aspire 45DDR — New Class A',
    description: 'The 2025 Entegra Coach Aspire 45DDR is a brand-new flagship Class A diesel motorhome on a Spartan K2 raised-rail chassis. Powered by a Cummins 12.9L turbo diesel, it offers four slide-outs, a full-wall slide, residential chef kitchen, king bed master with tile shower, and a half bath. Includes a 12kW Onan generator, 1,200W solar system, and 125-gallon fresh water tank. Sleeps 6 and seats 8. Stock #MH-0012.',
    price: 725000, currency: 'USD',
    brand: 'Entegra Coach', model: 'Aspire 45DDR', model_year: 2025,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Diesel',
    engine: 'Cummins 12.9L Turbo Diesel (605 HP)',
    drive_type: 'RWD', color: 'Graphite Metallic',
    property_type: 'Class A Motorhome',
    sleeping_capacity: '6', seating_capacity: '8',
    bathroom: 'Spa Master Bath with Tile Shower + Half Bath', kitchen: 'Residential Chef Kitchen with 24-cu-ft Fridge', water_tank: '125 gallons',
    vin: 'KCO0012MH0012', stock_number: 'MH-0012',
    listing_status: 'sale',
    images: buildGallery([17870274, 17273587, 16746357, 12329017, 12709207, 7061407]),
    rating: 5.0, rating_count: 18, favorite_count: 16,
    features: ['4 Slide-outs', 'Full-Wall Slide', 'Cummins 12.9L Diesel', 'Residential Chef Kitchen', '12kW Generator', '1,200W Solar', 'Spa Master Bath'],
  },
  {
    property_id: 'KCO-MH0013', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Newmar Dutch Star 4369 — New Class A',
    description: 'The 2026 Newmar Dutch Star 4369 is a brand-new pinnacle Class A diesel motorhome on a Spartan K3 chassis. Powered by a Cummins 12.9L turbo diesel delivering 605 horsepower, it features four slide-outs, a full-wall slide, chef kitchen with 24-cu-ft residential refrigerator, king-size Sleep Number bed, and a spa-like master bath with tile shower. Includes a 21kW Cummins Onan generator, 1,200W solar system, and 125-gallon fresh water tank. Sleeps 6 and seats 8. Stock #MH-0013.',
    price: 775000, currency: 'USD',
    brand: 'Newmar', model: 'Dutch Star 4369', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Diesel',
    engine: 'Cummins 12.9L Turbo Diesel (605 HP)',
    drive_type: 'RWD', color: 'Chestnut Brown',
    property_type: 'Class A Motorhome',
    sleeping_capacity: '6', seating_capacity: '8',
    bathroom: 'Spa Master Bath with Tile Shower', kitchen: 'Chef Kitchen with 24-cu-ft Residential Fridge', water_tank: '125 gallons',
    vin: 'KCO0013MH0013', stock_number: 'MH-0013',
    listing_status: 'sale',
    images: buildGallery([34287638, 34613381, 6187660, 12329134, 20394610, 7746070]),
    rating: 4.9, rating_count: 21, favorite_count: 19,
    features: ['4 Slide-outs', 'Full-Wall Slide', 'Cummins 605 HP', 'Sleep Number Bed', '21kW Generator', '1,200W Solar', 'Spa Master Bath'],
  },
  {
    property_id: 'KCO-MH0014', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Tiffin Allegro Bus 40IP — New Class A',
    description: 'The 2026 Tiffin Allegro Bus 40IP is a brand-new luxury Class A diesel pusher on a Freightliner XCM raised-rail chassis. Powered by a Cummins 12.9L turbo diesel, it offers four slide-outs, a residential kitchen, king bed master suite, and a full bath with glass shower. Includes a 12kW Onan generator, 800W solar system, and 100-gallon fresh water tank. Sleeps 6 and seats 7. Stock #MH-0014.',
    price: 689900, currency: 'USD',
    brand: 'Tiffin', model: 'Allegro Bus 40IP', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Diesel',
    engine: 'Cummins 12.9L Turbo Diesel (500 HP)',
    drive_type: 'RWD', color: 'Platinum Silver',
    property_type: 'Class A Motorhome',
    sleeping_capacity: '6', seating_capacity: '7',
    bathroom: 'Full Bath with Glass Shower', kitchen: 'Residential Kitchen with 21-cu-ft Fridge', water_tank: '100 gallons',
    vin: 'KCO0014MH0014', stock_number: 'MH-0014',
    listing_status: 'sale',
    images: buildGallery([16763286, 16763335, 6946422, 11392441, 7476253, 28457986]),
    rating: 4.9, rating_count: 27, favorite_count: 23,
    features: ['4 Slide-outs', 'Cummins 500 HP', 'Residential Kitchen', 'King Bed', '12kW Generator', '800W Solar', '100 Gal Water'],
  },
  {
    property_id: 'KCO-MH0015', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Fleetwood Bounder 35K — New Class A',
    description: 'The 2026 Fleetwood Bounder 35K is a brand-new gas Class A motorhome on a Ford F-53 chassis. Powered by a 7.3L V8 gasoline engine, it offers three slide-outs, a bunkhouse with three bunks, a rear master queen bed, full bath, and a kitchen with 16-cu-ft refrigerator, three-burner cooktop, and oven. Includes a 5.5kW Onan gas generator and 75-gallon fresh water tank. Sleeps 8 and seats 8. Stock #MH-0015.',
    price: 169900, currency: 'USD',
    brand: 'Fleetwood', model: 'Bounder 35K', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Gasoline',
    engine: '7.3L V8 (350 HP)',
    drive_type: 'RWD', color: 'White with Blue Decals',
    property_type: 'Class A Motorhome',
    sleeping_capacity: '8', seating_capacity: '8',
    bathroom: 'Full Bath + Half Bath', kitchen: 'Kitchen with 16-cu-ft Fridge and Oven', water_tank: '75 gallons',
    vin: 'KCO0015MH0015', stock_number: 'MH-0015',
    listing_status: 'sale',
    images: buildGallery([11113256, 14523224, 6946132, 3935313, 4572032, 8135109]),
    rating: 4.6, rating_count: 52, favorite_count: 31,
    features: ['3 Slide-outs', 'Bunkhouse', '7.3L V8', '5.5kW Generator', 'Sleeps 8', '16-cu-ft Fridge', '75 Gal Water'],
  },
  {
    property_id: 'KCO-MH0016', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Renegade Verona LE 40VBE — New Super C',
    description: 'The 2026 Renegade Verona LE 40VBE is a brand-new premium Super C motorhome on a Freightliner M2 chassis. Powered by a Cummins 6.7L turbo diesel, it features a spacious slide-out living area, residential kitchen, king bed master suite, full bath with tile shower, and a large garage. Includes a 10kW generator, 800W solar system, and 100-gallon fresh water tank. Sleeps 5 and seats 6. Stock #MH-0016.',
    price: 549900, currency: 'USD',
    brand: 'Renegade', model: 'Verona LE 40VBE', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Diesel',
    engine: 'Cummins 6.7L Turbo Diesel (360 HP)',
    drive_type: 'RWD', color: 'Phantom Black',
    property_type: 'Super C Motorhome',
    sleeping_capacity: '5', seating_capacity: '6',
    bathroom: 'Full Bath with Tile Shower', kitchen: 'Residential Kitchen with Full-Size Fridge', water_tank: '100 gallons',
    vin: 'KCO0016MH0016', stock_number: 'MH-0016',
    listing_status: 'sale',
    images: buildGallery([14810447, 14816413, 9354747, 10750999, 7667366, 18071801]),
    rating: 4.9, rating_count: 19, favorite_count: 15,
    features: ['Super C Freightliner', 'Cummins 6.7L Diesel', 'Residential Kitchen', 'King Bed', 'Garage', '10kW Generator', '800W Solar'],
  },
  {
    property_id: 'KCO-MH0017', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Dynamax Isata 5 30FW — New Super C',
    description: 'The 2026 Dynamax Isata 5 30FW is a brand-new adventure-ready Super C motorhome on a Ram 5500 chassis. Powered by a 6.7L Cummins turbo diesel, it offers a rear full-wall slide with a cozy living area, slide-out galley, rear queen bed, full bath with shower, and a garage. Includes a 5kW Onan generator and 55-gallon fresh water tank. Sleeps 5 and seats 6. Stock #MH-0017.',
    price: 289900, currency: 'USD',
    brand: 'Dynamax', model: 'Isata 5 30FW', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Diesel',
    engine: '6.7L Cummins Turbo Diesel (360 HP)',
    drive_type: 'RWD', color: 'Granite Gray',
    property_type: 'Super C Motorhome',
    sleeping_capacity: '5', seating_capacity: '6',
    bathroom: 'Full Bath with Shower', kitchen: 'Slide-Out Galley with Three-Burner Cooktop', water_tank: '55 gallons',
    vin: 'KCO0017MH0017', stock_number: 'MH-0017',
    listing_status: 'sale',
    images: buildGallery([14924831, 15276639, 6187664, 36036606, 17444987, 18869571]),
    rating: 4.7, rating_count: 33, favorite_count: 21,
    features: ['Super C Ram 5500', '6.7L Cummins Diesel', 'Rear Full-Wall Slide', 'Garage', '5kW Generator', 'Sleeps 5'],
  },
  {
    property_id: 'KCO-MH0018', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2025 Jayco Redhawk 31F — New Class C',
    description: 'The 2025 Jayco Redhawk 31F is a brand-new family Class C motorhome on a Ford E-450 chassis. Powered by a 7.3L V8 gasoline engine, it offers a slide-out dinette, cab-over bunk, rear double bed, full bath with shower, and a kitchen with three-burner cooktop, oven, and refrigerator. Includes a 4kW Onan gas generator and 50-gallon fresh water tank. Sleeps 8 and seats 8. Stock #MH-0018.',
    price: 129900, currency: 'USD',
    brand: 'Jayco', model: 'Redhawk 31F', model_year: 2025,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Gasoline',
    engine: '7.3L V8 (350 HP)',
    drive_type: 'RWD', color: 'White with Burgundy Accents',
    property_type: 'Class C Motorhome',
    sleeping_capacity: '8', seating_capacity: '8',
    bathroom: 'Full Bath with Shower', kitchen: 'Kitchen with Three-Burner Cooktop and Oven', water_tank: '50 gallons',
    vin: 'KCO0018MH0018', stock_number: 'MH-0018',
    listing_status: 'sale',
    images: buildGallery([17674305, 27620842, 6188010, 12329421, 6946126, 6970023]),
    rating: 4.5, rating_count: 61, favorite_count: 34,
    features: ['Slide-Out Dinette', 'Cab-Over Bunk', '7.3L V8', '4kW Generator', 'Oven', 'Sleeps 8', '50 Gal Water'],
  },
  {
    property_id: 'KCO-MH0019', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Thor ACE 33.1 — New Class A',
    description: 'The 2026 Thor Motor Coach ACE 33.1 is a brand-new gas Class A motorhome on a Ford F-53 chassis. Powered by a 7.3L V8 gasoline engine, it features three slide-outs, a cab-over drop-down bunk, rear king bed, full bath with shower, and a kitchen with three-burner cooktop, oven, and 16-cu-ft refrigerator. Includes a 4kW Onan generator and 65-gallon fresh water tank. Sleeps 8 and seats 8. Stock #MH-0019.',
    price: 159900, currency: 'USD',
    brand: 'Thor Motor Coach', model: 'ACE 33.1', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Gasoline',
    engine: '7.3L V8 (350 HP)',
    drive_type: 'RWD', color: 'Pearl White',
    property_type: 'Class A Motorhome',
    sleeping_capacity: '8', seating_capacity: '8',
    bathroom: 'Full Bath with Shower', kitchen: 'Kitchen with Three-Burner Cooktop and 16-cu-ft Fridge', water_tank: '65 gallons',
    vin: 'KCO0019MH0019', stock_number: 'MH-0019',
    listing_status: 'sale',
    images: buildGallery([28897042, 386025, 38799552, 15240765, 14735945, 7546549]),
    rating: 4.6, rating_count: 44, favorite_count: 25,
    features: ['3 Slide-outs', 'Drop-Down Bunk', '7.3L V8', '4kW Generator', 'King Bed', '16-cu-ft Fridge', 'Sleeps 8'],
  },
  {
    property_id: 'KCO-MH0020', listing_type: 'vehicle', category: 'Motorhomes',
    title: '2026 Winnebago Ekos 27A — New Class B+',
    description: 'The 2026 Winnebago Ekos 27A is a brand-new Class B+ motorhome on a Ford Transit AWD chassis. Powered by a 3.5L EcoBoost V6, it offers a full bath with shower, a galley with two-burner cooktop and 12V fridge, and a dinette that converts to a bed plus a rear bed. Includes a 300W solar system and 35-gallon fresh water tank. Sleeps 4 and seats 6. Stock #MH-0020.',
    price: 149900, currency: 'USD',
    brand: 'Winnebago', model: 'Ekos 27A', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '10-Speed Auto', fuel_type: 'Gasoline',
    engine: '3.5L EcoBoost V6 (310 HP)',
    drive_type: 'AWD', color: 'Arctic White',
    property_type: 'Class B+ Motorhome',
    sleeping_capacity: '4', seating_capacity: '6',
    bathroom: 'Full Bath with Shower', kitchen: 'Galley with Two-Burner Cooktop and 12V Fridge', water_tank: '35 gallons',
    vin: 'KCO0020MH0020', stock_number: 'MH-0020',
    listing_status: 'sale',
    images: buildGallery([17816414, 24363123, 6187998, 7476237, 14213436, 19857270]),
    rating: 4.8, rating_count: 30, favorite_count: 22,
    features: ['Ford Transit AWD', '3.5L EcoBoost V6', '300W Solar', 'Full Bath', 'Sleeps 4', '35 Gal Water'],
  },
];

export function getMotorhomeById(id) {
  return MOTORHOME_LISTINGS.find(m => m.property_id === id) || null;
}
