// Beautiful Pets — 15 world-famous dog breeds for sale, each with its own
// set of real photos from Wikimedia Commons. No photo is reused.

const WM = (p) => `https://upload.wikimedia.org/wikipedia/commons/thumb/${p}`;
const WMO = (p) => `https://upload.wikimedia.org/wikipedia/commons/${p}`;

export const PET_LISTINGS = [
  {
    property_id: 'W10248', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Poodle',
    description: 'A beautiful red Standard Poodle with an elegant, non-shedding hypoallergenic coat. This bright and affectionate companion is fully vaccinated, microchipped, and health-checked by a certified vet. Poodles are among the most intelligent dog breeds and love learning tricks, joining walks, and curling up beside their family. Ready to meet her new forever home.',
    price: 1850, currency: 'USD', country: 'France', country_code: 'FR',
    breed: 'Poodle', age: '10 Months', gender: 'Female', color: 'Red / Apricot', size: '45–70 lbs',
    images: [WM('1/19/Red_Standard_Poodle_Abigail_by_Don_Ramey_Logan.jpg/1280px-Red_Standard_Poodle_Abigail_by_Don_Ramey_Logan.jpg'), WM('7/7d/Bell_Poodle_Dog_2021.jpg/1280px-Bell_Poodle_Dog_2021.jpg')],
    rating: 4.9, rating_count: 168, favorite_count: 132,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Hypoallergenic Coat', 'Dewormed'],
    highlights: ['Non-shedding hypoallergenic coat', 'One of the most intelligent breeds', 'Great with families and children'],
  },
  {
    property_id: 'W10249', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Beagle',
    description: 'A cheerful, happy-go-lucky Beagle puppy with the classic tricolor coat and those big soulful eyes. Beagles are gentle, sociable, and wonderful with children and other pets. This little boy is playful, full of energy, and already learning basic obedience. Fully vaccinated, microchipped, and vet checked.',
    price: 850, currency: 'USD', country: 'United Kingdom', country_code: 'GB',
    breed: 'Beagle', age: '12 Weeks', gender: 'Male', color: 'Tricolor (Black, Tan & White)', size: '20–25 lbs',
    images: [WM('f/f9/A_beagle_standing_in_a_dog_park.jpg/1280px-A_beagle_standing_in_a_dog_park.jpg'), WM('6/63/A_Beagle_standing_on_the_beach.jpg/1280px-A_Beagle_standing_on_the_beach.jpg')],
    rating: 4.8, rating_count: 141, favorite_count: 118,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Excellent With Children', 'House Training in Progress'],
    highlights: ['Gentle and great with kids', 'Sociable with other pets', 'Playful family companion'],
  },
  {
    property_id: 'W10250', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Shih Tzu',
    description: 'A sweet, cuddly Shih Tzu with a soft white-and-brown coat and a warm, affectionate personality. Shih Tzus were bred to be companion dogs, and this little girl lives up to that — always happy to sit on your lap or follow you around the house. Fully vaccinated, microchipped, and groomed regularly.',
    price: 1100, currency: 'USD', country: 'China', country_code: 'CN',
    breed: 'Shih Tzu', age: '16 Weeks', gender: 'Female', color: 'White & Brown', size: '9–16 lbs',
    images: [WM('d/d3/Shih_tzu_dog.jpg/1280px-Shih_tzu_dog.jpg'), WMO('0/01/Shih_Tzu_portrait_show_dog.jpg')],
    rating: 4.7, rating_count: 122, favorite_count: 96,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Perfect Lap Dog', 'Great for Apartments'],
    highlights: ['Affectionate lap companion', 'Ideal for apartment living', 'Devoted to its family'],
  },
  {
    property_id: 'W10251', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Boxer',
    description: 'A handsome fawn Boxer puppy with a strong, athletic build and a goofy, lovable grin. Boxers are loyal, playful, and endlessly protective of their families, yet gentle with children. This boy is confident, eager to please, and thrives with an active household. Fully vaccinated, microchipped, and vet checked.',
    price: 950, currency: 'USD', country: 'Germany', country_code: 'DE',
    breed: 'Boxer', age: '10 Weeks', gender: 'Male', color: 'Fawn', size: '55–70 lbs',
    images: [WM('5/59/Boxer_dog_in_iran.jpg/1280px-Boxer_dog_in_iran.jpg'), WM('b/b5/Boxer_%28dog%29_%2C_Iran_06.jpg/1280px-Boxer_%28dog%29_%2C_Iran_06.jpg')],
    rating: 4.8, rating_count: 154, favorite_count: 109,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Great Watchdog', 'Playful & Energetic'],
    highlights: ['Loyal and protective', 'Excellent with children', 'Full of playful energy'],
  },
  {
    property_id: 'W10252', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Cane Corso',
    description: 'A majestic Italian Cane Corso with a powerful, dignified presence and a loyal heart. Known as the guardian of the family, the Cane Corso is calm, confident, and deeply devoted to its owners. This young male is well socialized, obedient, and has a calm temperament. Fully vaccinated, microchipped, and health checked.',
    price: 1650, currency: 'USD', country: 'Italy', country_code: 'IT',
    breed: 'Cane Corso', age: '8 Months', gender: 'Male', color: 'Gray', size: '90–110 lbs',
    images: [WMO('3/36/Cane_Corso_maschio.jpg'), WMO('7/79/Italian_Corso_Dog_grey_male_2.jpg')],
    rating: 4.9, rating_count: 97, favorite_count: 88,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Calm & Confident', 'Well Socialized'],
    highlights: ['Noble guardian of the family', 'Calm and obedient temperament', 'Deeply loyal to its owners'],
  },
  {
    property_id: 'W10253', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Border Collie',
    description: 'A bright-eyed black-and-white Border Collie — the world\'s most intelligent dog breed. This girl is incredibly smart, agile, and eager to learn; she picks up new commands in minutes and adores outdoor adventures. She would thrive in an active home that loves long walks and training games. Fully vaccinated, microchipped, and vet checked.',
    price: 900, currency: 'USD', country: 'United Kingdom', country_code: 'GB',
    breed: 'Border Collie', age: '12 Weeks', gender: 'Female', color: 'Black & White', size: '30–55 lbs',
    images: [WM('5/59/Border_Collie_in_Sogne.jpg/1280px-Border_Collie_in_Sogne.jpg'), WM('c/cd/Border_collie_blue_merle.jpg/1280px-Border_collie_blue_merle.jpg')],
    rating: 4.8, rating_count: 178, favorite_count: 143,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Highly Trainable', 'Loves Outdoor Activity'],
    highlights: ['World\'s most intelligent breed', 'Learns commands in minutes', 'Perfect active companion'],
  },
  {
    property_id: 'W10254', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Dalmatian',
    description: 'A striking show-quality Dalmatian with the classic white coat and jet-black spots. Dalmatians are athletic, elegant, and endlessly loyal companions that love to run and play. This young male has a gentle, friendly temperament and gets along wonderfully with people. Fully vaccinated, microchipped, and vet checked.',
    price: 1250, currency: 'USD', country: 'Croatia', country_code: 'HR',
    breed: 'Dalmatian', age: '7 Months', gender: 'Male', color: 'White with Black Spots', size: '45–70 lbs',
    images: [WMO('6/68/Sun_Dog_Dalmatian.jpg'), WM('e/e6/Dalmatian-sitting.jpg/1280px-Dalmatian-sitting.jpg')],
    rating: 4.8, rating_count: 133, favorite_count: 104,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Athletic & Elegant', 'Friendly Temperament'],
    highlights: ['Iconic spotted coat', 'Athletic running companion', 'Gentle and sociable nature'],
  },
  {
    property_id: 'W10255', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'English Bulldog',
    description: 'A charming English Bulldog puppy with that unmistakable wrinkled face and comical, laid-back attitude. Bulldogs are loyal, gentle, and famously great with children — the perfect family companion. This girl loves cozy naps as much as short, playful walks. Fully vaccinated, microchipped, and vet checked.',
    price: 1800, currency: 'USD', country: 'United Kingdom', country_code: 'GB',
    breed: 'English Bulldog', age: '14 Weeks', gender: 'Female', color: 'Tan & White', size: '40–50 lbs',
    images: [WM('9/94/English_Bulldog_Ouside.jpg/1280px-English_Bulldog_Ouside.jpg'), WMO('1/1f/English_Bulldog_Ercole.jpg')],
    rating: 4.9, rating_count: 187, favorite_count: 165,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Wonderful With Children', 'Calm & Affectionate'],
    highlights: ['Famous gentle temperament', 'Fantastic with kids', 'Easygoing family companion'],
  },
  {
    property_id: 'W10256', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Akita',
    description: 'A proud and regal Akita Inu with a thick red-and-white double coat and the quiet confidence of a born guardian. Akitas are loyal, courageous, and form deep bonds with their family. This young male is well trained, socialized, and wonderfully calm indoors. Fully vaccinated, microchipped, and vet checked.',
    price: 1500, currency: 'USD', country: 'Japan', country_code: 'JP',
    breed: 'Akita', age: '10 Months', gender: 'Male', color: 'Red & White', size: '70–130 lbs',
    images: [WM('5/5e/Akita_Inu_20191115-143723-1.jpg/1280px-Akita_Inu_20191115-143723-1.jpg'), WM('7/7a/Akita_Inu_Eddy.jpg/1280px-Akita_Inu_Eddy.jpg')],
    rating: 4.8, rating_count: 116, favorite_count: 101,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Quiet & Dignified', 'Loyal Guardian'],
    highlights: ['Courageous and loyal guardian', 'Calm and dignified indoors', 'Deep devotion to family'],
  },
  {
    property_id: 'W10257', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Welsh Corgi',
    description: 'A delightful Pembroke Welsh Corgi with the famous foxy face, big upright ears, and those adorable short legs. Corgis are smart, cheerful, and surprisingly athletic — full of personality and always happy to be the center of attention. This girl is affectionate with everyone she meets. Fully vaccinated, microchipped, and vet checked.',
    price: 1300, currency: 'USD', country: 'United Kingdom', country_code: 'GB',
    breed: 'Welsh Corgi', age: '12 Weeks', gender: 'Female', color: 'Sable & White', size: '22–31 lbs',
    images: [WM('7/7c/Welsh_Corgi_%282023-07-21%29_E911a_02.jpg/1280px-Welsh_Corgi_%282023-07-21%29_E911a_02.jpg'), WM('6/6c/Welsh_Corgi_%282023-07-21%29_E911a_01.jpg/1280px-Welsh_Corgi_%282023-07-21%29_E911a_01.jpg')],
    rating: 4.9, rating_count: 203, favorite_count: 171,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Big Personality', 'Loves Playtime'],
    highlights: ['Famous foxy Corgi look', 'Smart and full of personality', 'Loyal and affectionate'],
  },
  {
    property_id: 'W10258', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Chihuahua',
    description: 'A tiny, big-hearted Chihuahua with a fawn coat and a huge personality in a pocket-sized body. Chihuahuas are devoted, brave, and make the perfect lap companion for any home — big or small. This little girl is confident, sweet, and loves to be carried around. Fully vaccinated, microchipped, and vet checked.',
    price: 750, currency: 'USD', country: 'Mexico', country_code: 'MX',
    breed: 'Chihuahua', age: '9 Weeks', gender: 'Female', color: 'Fawn', size: '4–6 lbs',
    images: [WM('3/3e/Chihuahua_%28dog%29_06.jpg/1280px-Chihuahua_%28dog%29_06.jpg'), WM('f/ff/Blubble_Head_English_Chihuahua_-_Warhol.jpg/1280px-Blubble_Head_English_Chihuahua_-_Warhol.jpg')],
    rating: 4.7, rating_count: 129, favorite_count: 98,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Perfect Travel Companion', 'Great for Apartments'],
    highlights: ['Pocket-sized sweetheart', 'Brave and devoted', 'Ideal for small homes'],
  },
  {
    property_id: 'W10259', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Pomeranian',
    description: 'A fluffy orange Pomeranian with a big personality and an even bigger heart. Pomeranians are lively, intelligent, and incredibly affectionate — always excited to see you and happy to show off. This little boy has a gorgeous plush double coat and a confident strut. Fully vaccinated, microchipped, and vet checked.',
    price: 950, currency: 'USD', country: 'Germany', country_code: 'DE',
    breed: 'Pomeranian', age: '11 Weeks', gender: 'Male', color: 'Orange', size: '3–7 lbs',
    images: [WM('e/ec/Pomeranian_Dog_-_Kolkata_2011-10-31_6420.JPG/1280px-Pomeranian_Dog_-_Kolkata_2011-10-31_6420.JPG'), WMO('b/b6/Pomeranian_orange_1.jpg')],
    rating: 4.8, rating_count: 145, favorite_count: 124,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Fluffy Plush Coat', 'Big Personality'],
    highlights: ['Gorgeous fluffy coat', 'Lively and affectionate', 'Perfect little companion'],
  },
  {
    property_id: 'W10260', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Papillon',
    description: 'An elegant Papillon with butterfly-like ears, a white-and-brown coat, and a bright, cheerful disposition. Papillons are playful, intelligent little dogs that are surprisingly athletic and love to learn. This sweet girl is social, gentle, and a joy to have around the house. Fully vaccinated, microchipped, and vet checked.',
    price: 800, currency: 'USD', country: 'Belgium', country_code: 'BE',
    breed: 'Papillon', age: '14 Weeks', gender: 'Female', color: 'White with Brown Patches', size: '5–10 lbs',
    images: [WM('2/2a/Papillon_portrait_Flickr.jpg/1280px-Papillon_portrait_Flickr.jpg'), WM('5/56/Papillon_doing_blep.jpg/1280px-Papillon_doing_blep.jpg')],
    rating: 4.7, rating_count: 108, favorite_count: 84,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Playful & Cheerful', 'Surprisingly Athletic'],
    highlights: ['Signature butterfly ears', 'Bright and eager to learn', 'Gentle family companion'],
  },
  {
    property_id: 'W10261', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Bloodhound',
    description: 'A noble black-and-tan Bloodhound with those famous droopy ears and one of the most powerful noses in the dog world. Bloodhounds are gentle, calm, and famously good-natured, with an incredible tracking instinct. This young male is affectionate and wonderfully patient. Fully vaccinated, microchipped, and vet checked.',
    price: 1200, currency: 'USD', country: 'Belgium', country_code: 'BE',
    breed: 'Bloodhound', age: '8 Months', gender: 'Male', color: 'Black & Tan', size: '80–110 lbs',
    images: [WM('1/18/Bloodhound_Trials_Feb_2008_-63_%282299861445%29.jpg/1280px-Bloodhound_Trials_Feb_2008_-63_%282299861445%29.jpg'), WMO('3/32/Bloodhound_423.jpg')],
    rating: 4.8, rating_count: 91, favorite_count: 76,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Gentle Giant', 'Incredible Tracker'],
    highlights: ['Remarkable tracking instinct', 'Gentle, patient temperament', 'Loyal and good-natured'],
  },
  {
    property_id: 'W10262', listing_type: 'pet', category: 'Pets', subcategory: 'Dogs',
    title: 'Greyhound',
    description: 'A sleek, elegant brindle Greyhound with the sleekest silhouette in the canine world — and a surprisingly gentle, calm nature indoors. Greyhounds are fast on the track and famously laid-back couch companions at home. This lovely girl is sweet, quiet, and adores people. Fully vaccinated, microchipped, and vet checked.',
    price: 1400, currency: 'USD', country: 'United Kingdom', country_code: 'GB',
    breed: 'Greyhound', age: '9 Months', gender: 'Female', color: 'Brindle', size: '60–70 lbs',
    images: [WM('4/4b/Brindle_greyhound%2C_New_Zealand.jpg/1280px-Brindle_greyhound%2C_New_Zealand.jpg'), WM('1/16/A_greyhound_walking_through_a_forest.jpg/1280px-A_greyhound_walking_through_a_forest.jpg')],
    rating: 4.8, rating_count: 119, favorite_count: 93,
    tags: ['For Sale'],
    availability_status: 'Available', stock_quantity: 1, condition: 'Healthy', warranty: '',
    features: ['Pedigree Registered', 'Fully Vaccinated', 'Microchipped', 'Vet Health Checked', 'Calm Indoor Nature', 'Gentle With Everyone'],
    highlights: ['Elegant, lightning-fast athlete', 'Famous couch-potato indoors', 'Sweet and gentle nature'],
  },
];
