// Truck listings — 30 curated trucks (small & big, new & classic).
// Every truck has its own dedicated set of 4 unique photos — no photo ID is
// shared between trucks, and no truck ships with an empty or broken gallery.

const PEXELS = (id, w = 1000) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}`;

// Each truck gets its own dedicated array of 4 unique image IDs — no ID is reused across trucks
const TRUCK_GALLERIES = {
  f150Lightning:  [12021856, 12384824, 12748714, 12748717],
  cybertruck:     [3089389, 2994335, 937668, 210063],
  rivianR1t:      [4388158, 8438569, 1525616, 17157308],
  fordMaverick:   [6200441, 528426, 29500770, 5652670],
  silveradoZ71:   [27689900, 28226938, 28502326, 29026609],
  sierraAt4:      [34611427, 35484520, 191738, 19499386],
  ram1500:        [27099096, 27756329, 28264496, 31550630],
  tundraTrdPro:   [5126931, 5438616, 33814734, 35497785],
  tacomaTrd:      [33081220, 33262905, 34875545, 34902065],
  coloradoZr2:    [5962471, 6075494, 35531283, 37177077],
  f250SuperDuty:  [12986023, 14692595, 11455717, 11456554],
  ram2500:        [37091323, 37378481, 2640023, 5126305],
  f150Raptor:     [14438397, 12780212, 13746779, 29627572],
  sierra2500hd:   [29255730, 33653651, 38448743, 38510741],
  peterbilt579:   [12676275, 12756876, 14206821, 14283065],
  kenworthW900:   [15828799, 16195433, 12765659, 12765663],
  volvoVnl780:    [15392185, 15830756, 2199293, 192364],
  cascadia:       [12261472, 13219418, 13802140, 14214416],
  intlLT:         [27128551, 28262064, 15684925, 18864730],
  kenworthT680:   [16023877, 17522979, 18468412, 2348359],
  volvoVnl760:    [262353, 27099095, 3752194, 3791193],
  peterbilt389:   [29226626, 32107429, 34357281, 35832746],
  mackGranite:    [15643000, 16209079, 18435588, 19274705],
  intlWrecker:    [32560104, 32667398, 190539, 190574],
  t880Tanker:     [37538286, 37753989, 4115457, 5696170],
  m2Reefer:       [7856880, 8405876, 37418725, 4489758],
  m2Box:          [6333640, 6539032, 1015555, 10963747],
  isuzuNqr:       [11053643, 12159230, 16341407, 241188],
  hino268:        [12765673, 13065691, 16002206, 16008763],
  f750Dump:       [21193074, 26586338, 93398, 15325401],
};

function buildGallery(ids) {
  return ids.map((id, i) => PEXELS(id, i === 0 ? 1200 : 1000));
}

export const TRUCK_LISTINGS = [
  {
    property_id: 'KCO-T0001', listing_type: 'vehicle', category: 'Trucks',
    title: 'Ford F-150 Lightning Pro 2026 — New',
    description: 'The 2026 Ford F-150 Lightning Pro is a brand-new all-electric pickup built for serious work. Dual electric motors deliver 426 horsepower and 775 lb-ft of instant torque, paired with a single-speed automatic transmission and 4WD. A striking blue exterior, 2,235 lbs of payload, and a 10,000 lb tow rating make it as capable as it is clean, with a 230-mile electric range and Pro Power Onboard. Stock #STK-T0001.',
    price: 62500, currency: 'USD',
    brand: 'Ford', model: 'F-150 Lightning Pro', model_year: 2026,
    condition: 'New', mileage: '0 mi',
    transmission: '1-Speed Auto', fuel_type: 'Electric',
    engine: 'Dual Electric Motor (426 HP, 775 lb-ft)',
    drive_type: '4WD', color: 'Blue',
    payload_capacity: '2,235 lbs', towing_capacity: '10,000 lbs',
    vin: 'FO202600001', stock_number: 'STK-T0001',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.f150Lightning),
    rating: 4.8, rating_count: 42, favorite_count: 31,
    features: ['Dual Electric Motor', '426 HP', '775 lb-ft Torque', '230-Mile Range', '4WD', 'Pro Power Onboard', 'SYNC 4A Infotainment', 'LED Headlights'],
  },
  {
    property_id: 'KCO-T0002', listing_type: 'vehicle', category: 'Trucks',
    title: 'Tesla Cybertruck 2025 — New',
    description: 'The 2025 Tesla Cybertruck is a brand-new all-electric pickup wrapped in ultra-hard stainless steel. A tri-motor powertrain rockets this futuristic truck from 0-60 in under 3 seconds while still offering a 2,500 lb payload and 11,000 lb towing capacity. Adaptive air suspension, four-wheel steering, and a 340-mile range put it in a league of its own. Stock #STK-T0002.',
    price: 79990, currency: 'USD',
    brand: 'Tesla', model: 'Cybertruck', model_year: 2025,
    condition: 'New', mileage: '0 mi',
    transmission: 'Single-Speed Auto', fuel_type: 'Electric',
    engine: 'Tri-Motor Electric (845 HP)',
    drive_type: '4WD', color: 'Silver',
    payload_capacity: '2,500 lbs', towing_capacity: '11,000 lbs',
    vin: 'TE202500002', stock_number: 'STK-T0002',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.cybertruck),
    rating: 4.6, rating_count: 38, favorite_count: 27,
    features: ['Tri-Motor AWD', 'Stainless Exoskeleton', 'Adaptive Air Suspension', 'Four-Wheel Steering', '340-Mile Range', 'Panoramic Roof', 'Autopilot', 'Powered Frunk & Tonneau'],
  },
  {
    property_id: 'KCO-T0003', listing_type: 'vehicle', category: 'Trucks',
    title: 'Rivian R1T 2025 — New',
    description: 'The 2025 Rivian R1T is a brand-new adventure-ready electric pickup. Quad motors generate 835 horsepower with a 0-60 time of 3.0 seconds, while a 1,760 lb payload and 11,000 lb tow rating handle the hard jobs. The gear tunnel, 149 cu-ft storage, and air suspension with rally mode make it the most versatile truck in its class. Stock #STK-T0003.',
    price: 71500, currency: 'USD',
    brand: 'Rivian', model: 'R1T', model_year: 2025,
    condition: 'New', mileage: '0 mi',
    transmission: 'Single-Speed Auto', fuel_type: 'Electric',
    engine: 'Quad Motor (835 HP)',
    drive_type: '4WD', color: 'Sand',
    payload_capacity: '1,760 lbs', towing_capacity: '11,000 lbs',
    vin: 'RI202500003', stock_number: 'STK-T0003',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.rivianR1t),
    rating: 4.7, rating_count: 33, favorite_count: 24,
    features: ['Quad Motor AWD', 'Air Suspension', 'Gear Tunnel', '11,000 lb Towing', 'Rally Mode', 'Glass Roof', 'Driver+ Assist', 'Frunk & Under-Bed Storage'],
  },
  {
    property_id: 'KCO-T0004', listing_type: 'vehicle', category: 'Trucks',
    title: 'Ford Maverick Lariat 2025 — New',
    description: 'The 2025 Ford Maverick Lariat is a brand-new compact hybrid pickup that pairs 37 mpg with real truck utility. A 2.5L hybrid powertrain delivers 191 horsepower while towing up to 4,000 lbs, and the clever FLEXBED storage system makes the 4.5-foot bed work harder. Big-truck capability, small-truck footprint, and a price that fits any driveway. Stock #STK-T0004.',
    price: 29800, currency: 'USD',
    brand: 'Ford', model: 'Maverick Lariat', model_year: 2025,
    condition: 'New', mileage: '0 mi',
    transmission: 'CVT Auto', fuel_type: 'Hybrid',
    engine: '2.5L I4 Hybrid (191 HP)',
    drive_type: 'FWD', color: 'Teal',
    payload_capacity: '1,500 lbs', towing_capacity: '4,000 lbs',
    vin: 'FO202500004', stock_number: 'STK-T0004',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.fordMaverick),
    rating: 4.6, rating_count: 51, favorite_count: 35,
    features: ['Hybrid Powertrain', '37 MPG City', 'FLEXBED Storage', 'SYNC 4', 'LED Headlights', 'Co-Pilot360', 'Spray-In Bedliner', 'Keyless Entry'],
  },
  {
    property_id: 'KCO-T0005', listing_type: 'vehicle', category: 'Trucks',
    title: 'Chevrolet Silverado 1500 Z71 2024 — New',
    description: 'The 2024 Chevrolet Silverado 1500 Z71 is a brand-new full-size pickup built for off-road capability and everyday utility. A 5.3L V8 produces 355 horsepower through a 10-speed automatic and 4WD drivetrain, with a 2,080 lb payload and 13,400 lb tow rating. The Z71 package adds skid plates, Rancho shocks, and all-terrain tires for confident trailering and weekend adventures. Stock #STK-T0005.',
    price: 52400, currency: 'USD',
    brand: 'Chevrolet', model: 'Silverado 1500 Z71', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: '10-Speed Auto', fuel_type: 'Gasoline',
    engine: '5.3L V8 (355 HP)',
    drive_type: '4WD', color: 'Red',
    payload_capacity: '2,080 lbs', towing_capacity: '13,400 lbs',
    vin: 'CH202400005', stock_number: 'STK-T0005',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.silveradoZ71),
    rating: 4.7, rating_count: 56, favorite_count: 38,
    features: ['Z71 Off-Road Package', 'Rancho Shocks', 'Skid Plates', 'All-Terrain Tires', '10-Speed Auto', 'Tow Package', 'Backup Camera', 'Apple CarPlay'],
  },
  {
    property_id: 'KCO-T0006', listing_type: 'vehicle', category: 'Trucks',
    title: 'GMC Sierra 1500 AT4 2024 — New',
    description: 'The 2024 GMC Sierra 1500 AT4 is a brand-new premium pickup dressed for the outdoors. A 3.0L Duramax turbo-diesel produces 305 horsepower and a massive 495 lb-ft of torque, mated to a 10-speed automatic and 4WD. The AT4 package brings a two-inch factory lift, Rancho monotube shocks, and skid plates, with an upscale interior and 13,300 lb tow rating. Stock #STK-T0006.',
    price: 58900, currency: 'USD',
    brand: 'GMC', model: 'Sierra 1500 AT4', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: '10-Speed Auto', fuel_type: 'Diesel',
    engine: '3.0L Duramax Turbo-Diesel (305 HP, 495 lb-ft)',
    drive_type: '4WD', color: 'Black',
    payload_capacity: '2,010 lbs', towing_capacity: '13,300 lbs',
    vin: 'GM202400006', stock_number: 'STK-T0006',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.sierraAt4),
    rating: 4.8, rating_count: 44, favorite_count: 30,
    features: ['Duramax Diesel', '2-Inch Factory Lift', 'Rancho Monotube Shocks', 'Skid Plates', 'MultiPro Tailgate', 'Heated Leather Seats', 'Head-Up Display', 'Google Built-In'],
  },
  {
    property_id: 'KCO-T0007', listing_type: 'vehicle', category: 'Trucks',
    title: 'Ram 1500 Laramie 2024 — New',
    description: 'The 2024 Ram 1500 Laramie is a brand-new full-size pickup that blends luxury with hauling. A 5.7L HEMI V8 with eTorque produces 395 horsepower, paired with an 8-speed automatic and 4WD. The coil-spring rear suspension delivers a car-like ride, while a 2,010 lb payload and 12,750 lb tow rating keep it fully capable. Inside, the 12-inch Uconnect screen and leather trim set the tone. Stock #STK-T0007.',
    price: 54700, currency: 'USD',
    brand: 'Ram', model: '1500 Laramie', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: '8-Speed Auto', fuel_type: 'Gasoline',
    engine: '5.7L HEMI V8 eTorque (395 HP)',
    drive_type: '4WD', color: 'Grey',
    payload_capacity: '2,010 lbs', towing_capacity: '12,750 lbs',
    vin: 'RA202400007', stock_number: 'STK-T0007',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.ram1500),
    rating: 4.7, rating_count: 61, favorite_count: 40,
    features: ['HEMI V8 eTorque', 'Coil-Spring Rear Suspension', '12-Inch Uconnect', 'Leather Trim', 'Air Suspension', '4WD', 'Blind-Spot Monitoring', 'Heated & Ventilated Seats'],
  },
  {
    property_id: 'KCO-T0008', listing_type: 'vehicle', category: 'Trucks',
    title: 'Toyota Tundra TRD Pro 2024 — New',
    description: 'The 2024 Toyota Tundra TRD Pro is a brand-new off-road flagship built around the i-FORCE MAX hybrid. A 3.4L twin-turbo V6 hybrid delivers 437 horsepower and 583 lb-ft, paired with a 10-speed automatic and full-time 4WD. FOX internal bypass shocks, 33-inch tires, and a multi-terrain monitor make it unstoppable on the trail, with an 11,450 lb tow rating for work duty. Stock #STK-T0008.',
    price: 61200, currency: 'USD',
    brand: 'Toyota', model: 'Tundra TRD Pro', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: '10-Speed Auto', fuel_type: 'Hybrid',
    engine: '3.4L Twin-Turbo V6 Hybrid (437 HP, 583 lb-ft)',
    drive_type: '4WD', color: 'White',
    payload_capacity: '1,600 lbs', towing_capacity: '11,450 lbs',
    vin: 'TO202400008', stock_number: 'STK-T0008',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.tundraTrdPro),
    rating: 4.8, rating_count: 49, favorite_count: 34,
    features: ['i-FORCE MAX Hybrid', 'FOX Internal Bypass Shocks', '33-Inch Tires', 'Multi-Terrain Monitor', 'Crawl Control', 'LED Light Bar', 'Heated Leather Seats', 'Panoramic Moonroof'],
  },
  {
    property_id: 'KCO-T0009', listing_type: 'vehicle', category: 'Trucks',
    title: 'Toyota Tacoma TRD Off-Road 2024 — New',
    description: 'The 2024 Toyota Tacoma TRD Off-Road is a brand-new midsize pickup legendary for durability. A 2.4L turbocharged i-FORCE four-cylinder produces 278 horsepower, paired with an 8-speed automatic and part-time 4WD. The TRD Off-Road package brings Bilstein remote-reservoir shocks, a locking rear differential, and Crawl Control, with a 1,710 lb payload and 6,500 lb tow rating. Stock #STK-T0009.',
    price: 38900, currency: 'USD',
    brand: 'Toyota', model: 'Tacoma TRD Off-Road', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: '8-Speed Auto', fuel_type: 'Gasoline',
    engine: '2.4L Turbo I4 (278 HP)',
    drive_type: '4WD', color: 'Green',
    payload_capacity: '1,710 lbs', towing_capacity: '6,500 lbs',
    vin: 'TO202400009', stock_number: 'STK-T0009',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.tacomaTrd),
    rating: 4.7, rating_count: 67, favorite_count: 45,
    features: ['Turbo i-FORCE Engine', 'Bilstein Shocks', 'Locking Rear Diff', 'Crawl Control', 'Multi-Terrain Select', 'Toyota Safety Sense', 'LED Headlights', 'Power Tailgate'],
  },
  {
    property_id: 'KCO-T0010', listing_type: 'vehicle', category: 'Trucks',
    title: 'Chevrolet Colorado ZR2 2024 — New',
    description: 'The 2024 Chevrolet Colorado ZR2 is a brand-new midsize truck engineered for the toughest trails. A 2.7L Turbo Plus four-cylinder delivers 310 horsepower and 430 lb-ft, mated to an 8-speed automatic with 4WD. Multimatic DSSV spool-valve dampers, a front electronic locker, and 33-inch tires give it class-leading off-road composure with a 7,700 lb tow rating. Stock #STK-T0010.',
    price: 49300, currency: 'USD',
    brand: 'Chevrolet', model: 'Colorado ZR2', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: '8-Speed Auto', fuel_type: 'Gasoline',
    engine: '2.7L Turbo I4 (310 HP, 430 lb-ft)',
    drive_type: '4WD', color: 'Grey',
    payload_capacity: '1,420 lbs', towing_capacity: '7,700 lbs',
    vin: 'CH202400010', stock_number: 'STK-T0010',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.coloradoZr2),
    rating: 4.6, rating_count: 39, favorite_count: 26,
    features: ['Multimatic DSSV Dampers', 'Front & Rear Lockers', '33-Inch Off-Road Tires', 'Off-Road Mode', 'Surround Vision', 'Bose Audio', 'Google Built-In', 'Heated Seats'],
  },
  {
    property_id: 'KCO-T0011', listing_type: 'vehicle', category: 'Trucks',
    title: 'Ford F-250 Super Duty 2022 — Used',
    description: 'The 2022 Ford F-250 Super Duty is a well-maintained used heavy-duty pickup ready for serious hauling. A 6.7L Power Stroke diesel V8 produces 475 horsepower and 1,050 lb-ft, paired with a 10-speed automatic and 4WD. With a 4,200 lb payload and 20,000 lb tow rating, it is the workhorse for trailers, boats, and equipment. Current mileage is 52,300 miles with full service history. Stock #STK-T0011.',
    price: 46500, currency: 'USD',
    brand: 'Ford', model: 'F-250 Super Duty', model_year: 2022,
    condition: 'Used', mileage: '52,300 mi',
    transmission: '10-Speed Auto', fuel_type: 'Diesel',
    engine: '6.7L Power Stroke V8 (475 HP, 1,050 lb-ft)',
    drive_type: '4WD', color: 'Black',
    payload_capacity: '4,200 lbs', towing_capacity: '20,000 lbs',
    vin: 'FO202200011', stock_number: 'STK-T0011',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.f250SuperDuty),
    rating: 4.7, rating_count: 58, favorite_count: 37,
    features: ['Power Stroke Diesel', 'Pro Trailer Backup Assist', 'Tow Package', '4WD', '360 Camera', 'SYNC 4', 'Heated Seats', 'Spray-In Bedliner'],
  },
  {
    property_id: 'KCO-T0012', listing_type: 'vehicle', category: 'Trucks',
    title: 'Ram 2500 Tradesman 2022 — Used',
    description: 'The 2022 Ram 2500 Tradesman is a reliable used heavy-duty truck powered by the legendary 6.7L Cummins turbo-diesel. It produces 370 horsepower and 850 lb-ft through a 6-speed automatic and 4WD, with a 3,140 lb payload and 17,000 lb tow rating. At 48,700 miles with full service records, this truck is built for years of dependable pulling. Stock #STK-T0012.',
    price: 42800, currency: 'USD',
    brand: 'Ram', model: '2500 Tradesman', model_year: 2022,
    condition: 'Used', mileage: '48,700 mi',
    transmission: '6-Speed Auto', fuel_type: 'Diesel',
    engine: '6.7L Cummins I6 (370 HP, 850 lb-ft)',
    drive_type: '4WD', color: 'Grey',
    payload_capacity: '3,140 lbs', towing_capacity: '17,000 lbs',
    vin: 'RA202200012', stock_number: 'STK-T0012',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.ram2500),
    rating: 4.6, rating_count: 44, favorite_count: 29,
    features: ['Cummins Diesel', 'Tow Package', '4WD', 'Backup Camera', 'Bed Liner', 'Running Boards', 'Bluetooth', 'Cruise Control'],
  },
  {
    property_id: 'KCO-T0013', listing_type: 'vehicle', category: 'Trucks',
    title: 'Ford F-150 Raptor 2018 — Used',
    description: 'The 2018 Ford F-150 Raptor is a well-kept used high-performance off-road pickup. A 3.5L EcoBoost V6 delivers 450 horsepower through a 10-speed automatic and 4WD, while FOX Racing shocks and 35-inch BFG tires handle desert-speed running. At 41,200 miles this Raptor still delivers its signature combination of speed, suspension travel, and a 12,000 lb tow rating. Stock #STK-T0013.',
    price: 58000, currency: 'USD',
    brand: 'Ford', model: 'F-150 Raptor', model_year: 2018,
    condition: 'Used', mileage: '41,200 mi',
    transmission: '10-Speed Auto', fuel_type: 'Gasoline',
    engine: '3.5L EcoBoost V6 (450 HP, 510 lb-ft)',
    drive_type: '4WD', color: 'White',
    payload_capacity: '1,200 lbs', towing_capacity: '12,000 lbs',
    vin: 'FO201800013', stock_number: 'STK-T0013',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.f150Raptor),
    rating: 4.8, rating_count: 73, favorite_count: 52,
    features: ['EcoBoost V6', 'FOX Racing Shocks', '35-Inch BFG Tires', 'Terrain Management', 'Baja Mode', 'Recaro Seats', 'LED Lighting', 'Tow Package'],
  },
  {
    property_id: 'KCO-T0014', listing_type: 'vehicle', category: 'Trucks',
    title: 'GMC Sierra 2500 HD Denali 2021 — Used',
    description: 'The 2021 GMC Sierra 2500 HD Denali is a meticulously maintained used heavy-duty truck wrapped in premium trim. The 6.6L Duramax turbo-diesel V8 produces 445 horsepower and 910 lb-ft through a 10-speed Allison automatic and 4WD, with a 3,900 lb payload and 18,500 lb tow rating. At 39,800 miles it includes the MultiPro tailgate, adaptive cruise, and a sumptuous leather cabin. Stock #STK-T0014.',
    price: 55900, currency: 'USD',
    brand: 'GMC', model: 'Sierra 2500 HD Denali', model_year: 2021,
    condition: 'Used', mileage: '39,800 mi',
    transmission: '10-Speed Allison Auto', fuel_type: 'Diesel',
    engine: '6.6L Duramax Turbo-Diesel V8 (445 HP, 910 lb-ft)',
    drive_type: '4WD', color: 'Silver',
    payload_capacity: '3,900 lbs', towing_capacity: '18,500 lbs',
    vin: 'GM202100014', stock_number: 'STK-T0014',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.sierra2500hd),
    rating: 4.7, rating_count: 36, favorite_count: 25,
    features: ['Duramax Diesel', 'Allison 10-Speed', 'MultiPro Tailgate', 'Adaptive Cruise', 'Heated & Ventilated Seats', '360 Camera', 'Bose Audio', 'Tow Package'],
  },
  {
    property_id: 'KCO-T0015', listing_type: 'vehicle', category: 'Trucks',
    title: 'Peterbilt 579 2025 — New',
    description: 'The 2025 Peterbilt 579 is a brand-new Class 8 semi engineered for long-haul efficiency and driver comfort. A PACCAR MX-13 12.9L diesel produces 510 horsepower through an Eaton 13-speed manual and 6x4 drivetrain. The black 70-inch sleeper cab, air-ride suspension, and 80,000 lb GCWR make it ideal for cross-country freight with advanced aerodynamics. Stock #STK-T0015.',
    price: 162000, currency: 'USD',
    brand: 'Peterbilt', model: '579', model_year: 2025,
    condition: 'New', mileage: '0 mi',
    transmission: 'Eaton 13-Speed Manual', fuel_type: 'Diesel',
    engine: 'PACCAR MX-13 12.9L I6 (510 HP)',
    drive_type: '6x4', color: 'Black',
    payload_capacity: 'N/A', towing_capacity: '80,000 lbs GCWR',
    vin: 'PE202500015', stock_number: 'STK-T0015',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.peterbilt579),
    rating: 4.9, rating_count: 28, favorite_count: 19,
    features: ['70-Inch Sleeper', 'Air Ride Suspension', 'PACCAR MX-13', 'Jake Brake', 'Cruise Control', 'GPS Navigation', 'ABS', 'Auxiliary Power Unit'],
  },
  {
    property_id: 'KCO-T0016', listing_type: 'vehicle', category: 'Trucks',
    title: 'Kenworth W900 2024 — New',
    description: 'The 2024 Kenworth W900 is a brand-new American classic of the highway. The long-hood conventional styling houses a PACCAR MX-13 diesel with 510 horsepower, an Eaton 13-speed manual, and a 6x4 drivetrain. A 76-inch sleeper, polished aluminum details, and an 80,000 lb GCWR make it a favorite for owner-operators who demand presence and power. Stock #STK-T0016.',
    price: 168500, currency: 'USD',
    brand: 'Kenworth', model: 'W900', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: 'Eaton 13-Speed Manual', fuel_type: 'Diesel',
    engine: 'PACCAR MX-13 12.9L I6 (510 HP)',
    drive_type: '6x4', color: 'Red',
    payload_capacity: 'N/A', towing_capacity: '80,000 lbs GCWR',
    vin: 'KE202400016', stock_number: 'STK-T0016',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.kenworthW900),
    rating: 4.8, rating_count: 24, favorite_count: 17,
    features: ['76-Inch Sleeper', 'Long-Hood Conventional', 'Polished Aluminum', 'Air Ride Cab', 'Jake Brake', 'Rear Diff Locks', 'Premium Sound', 'Chrome Exhaust'],
  },
  {
    property_id: 'KCO-T0017', listing_type: 'vehicle', category: 'Trucks',
    title: 'Volvo VNL 780 2024 — New',
    description: 'The 2024 Volvo VNL 780 is a brand-new Class 8 tractor known for safety and fuel economy. A Volvo D13 diesel produces 455 horsepower through an I-Shift automated transmission and 6x4 drivetrain. The 70-inch Globetrotter sleeper, stability systems, and camera-based safety suite deliver a comfortable and secure 80,000 lb GCWR work environment. Stock #STK-T0017.',
    price: 148000, currency: 'USD',
    brand: 'Volvo', model: 'VNL 780', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: 'Volvo I-Shift Automated', fuel_type: 'Diesel',
    engine: 'Volvo D13 12.8L I6 (455 HP)',
    drive_type: '6x4', color: 'White',
    payload_capacity: 'N/A', towing_capacity: '80,000 lbs GCWR',
    vin: 'VO202400017', stock_number: 'STK-T0017',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.volvoVnl780),
    rating: 4.8, rating_count: 26, favorite_count: 18,
    features: ['I-Shift Automated', 'Volvo D13', 'Globetrotter Sleeper', 'Collision Warning', 'Lane Keeping', 'Air Suspension', 'Fuel Efficiency Package', 'LED Lighting'],
  },
  {
    property_id: 'KCO-T0018', listing_type: 'vehicle', category: 'Trucks',
    title: 'Freightliner Cascadia 2023 — Used',
    description: 'The 2023 Freightliner Cascadia is a well-maintained used semi built for fuel-efficient long-haul work. A Detroit DD15 14.8L diesel produces 505 horsepower through a Detroit DT12 automated transmission and 6x4 drivetrain. The 72-inch sleeper, aerodynamic styling, and 80,000 lb GCWR make it a proven revenue producer at 88,600 miles. Stock #STK-T0018.',
    price: 112000, currency: 'USD',
    brand: 'Freightliner', model: 'Cascadia', model_year: 2023,
    condition: 'Used', mileage: '88,600 mi',
    transmission: 'Detroit DT12 Automated', fuel_type: 'Diesel',
    engine: 'Detroit DD15 14.8L I6 (505 HP)',
    drive_type: '6x4', color: 'White',
    payload_capacity: 'N/A', towing_capacity: '80,000 lbs GCWR',
    vin: 'FR202300018', stock_number: 'STK-T0018',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.cascadia),
    rating: 4.7, rating_count: 22, favorite_count: 15,
    features: ['Detroit DD15', 'DT12 Automated', '72-Inch Sleeper', 'Aerodynamic Package', 'Collision Mitigation', 'Active Lane Assist', 'Air Ride', 'Fuel-Efficient Axle'],
  },
  {
    property_id: 'KCO-T0019', listing_type: 'vehicle', category: 'Trucks',
    title: 'International LT 2022 — Used',
    description: 'The 2022 International LT is a dependable used over-the-road tractor with strong bones. A Cummins X15 diesel produces 500 horsepower through an Eaton Endurant 12-speed automated transmission and 6x4 drivetrain. The 73-inch sleeper and 80,000 lb GCWR suit regional and national freight, with 121,400 miles and complete maintenance history. Stock #STK-T0019.',
    price: 98500, currency: 'USD',
    brand: 'International', model: 'LT', model_year: 2022,
    condition: 'Used', mileage: '121,400 mi',
    transmission: 'Eaton Endurant 12-Speed Auto', fuel_type: 'Diesel',
    engine: 'Cummins X15 15L I6 (500 HP)',
    drive_type: '6x4', color: 'Blue',
    payload_capacity: 'N/A', towing_capacity: '80,000 lbs GCWR',
    vin: 'IN202200019', stock_number: 'STK-T0019',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.intlLT),
    rating: 4.6, rating_count: 19, favorite_count: 13,
    features: ['Cummins X15', 'Endurant Automated', '73-Inch Sleeper', 'Bendix Safety Suite', 'Air Ride', 'Refrigerator', 'Inverter', 'Maintenance Records'],
  },
  {
    property_id: 'KCO-T0020', listing_type: 'vehicle', category: 'Trucks',
    title: 'Kenworth T680 2020 — Used',
    description: 'The 2020 Kenworth T680 is a clean used aero semi known for uptime and fuel economy. A PACCAR MX-13 diesel delivers 485 horsepower through a PACCAR automated transmission and 6x4 drivetrain. The 76-inch sleeper, smart dash, and 80,000 lb GCWR made it a fleet favorite; 136,200 miles with a solid service record. Stock #STK-T0020.',
    price: 95000, currency: 'USD',
    brand: 'Kenworth', model: 'T680', model_year: 2020,
    condition: 'Used', mileage: '136,200 mi',
    transmission: 'PACCAR Automated', fuel_type: 'Diesel',
    engine: 'PACCAR MX-13 12.9L I6 (485 HP)',
    drive_type: '6x4', color: 'White',
    payload_capacity: 'N/A', towing_capacity: '80,000 lbs GCWR',
    vin: 'KE202000020', stock_number: 'STK-T0020',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.kenworthT680),
    rating: 4.7, rating_count: 20, favorite_count: 14,
    features: ['PACCAR MX-13', 'PACCAR Automated', '76-Inch Sleeper', 'Aerodynamic Hood', 'Air Ride', 'Cruise Control', 'Camera System', 'Service Records'],
  },
  {
    property_id: 'KCO-T0021', listing_type: 'vehicle', category: 'Trucks',
    title: 'Volvo VNL 760 2021 — Used',
    description: 'The 2021 Volvo VNL 760 is a well-cared-for used Class 8 tractor with a roomy 70-inch sleeper. A Volvo D13 diesel produces 425 horsepower through an I-Shift automated transmission and 6x4 drivetrain. Volvo stability and safety systems combine with an 80,000 lb GCWR, and the truck shows 118,900 miles. Stock #STK-T0021.',
    price: 88000, currency: 'USD',
    brand: 'Volvo', model: 'VNL 760', model_year: 2021,
    condition: 'Used', mileage: '118,900 mi',
    transmission: 'Volvo I-Shift Automated', fuel_type: 'Diesel',
    engine: 'Volvo D13 12.8L I6 (425 HP)',
    drive_type: '6x4', color: 'White',
    payload_capacity: 'N/A', towing_capacity: '80,000 lbs GCWR',
    vin: 'VO202100021', stock_number: 'STK-T0021',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.volvoVnl760),
    rating: 4.6, rating_count: 18, favorite_count: 12,
    features: ['Volvo D13', 'I-Shift Automated', '70-Inch Sleeper', 'Stability Control', 'Air Suspension', 'Blind Spot System', 'Refrigerator', 'Maintenance History'],
  },
  {
    property_id: 'KCO-T0022', listing_type: 'vehicle', category: 'Trucks',
    title: 'Peterbilt 389 Classic 2015 — Used',
    description: 'The 2015 Peterbilt 389 is a beautifully kept classic conventional with timeless long-hood styling. A Caterpillar C15 diesel produces 550 horsepower through an Eaton 18-speed manual and 6x4 drivetrain. Polished stainless stacks, a 72-inch sleeper, and an 80,000 lb GCWR make this a statement truck for the open road at 342,000 miles. Stock #STK-T0022.',
    price: 74000, currency: 'USD',
    brand: 'Peterbilt', model: '389 Classic', model_year: 2015,
    condition: 'Used', mileage: '342,000 mi',
    transmission: 'Eaton 18-Speed Manual', fuel_type: 'Diesel',
    engine: 'Caterpillar C15 15.2L I6 (550 HP)',
    drive_type: '6x4', color: 'White',
    payload_capacity: 'N/A', towing_capacity: '80,000 lbs GCWR',
    vin: 'PE201500022', stock_number: 'STK-T0022',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.peterbilt389),
    rating: 4.8, rating_count: 31, favorite_count: 22,
    features: ['Caterpillar C15', '18-Speed Manual', '72-Inch Sleeper', 'Polished Stacks', 'Chrome Package', 'Air Ride', 'Dual Fuel Tanks', 'Well Documented'],
  },
  {
    property_id: 'KCO-T0023', listing_type: 'vehicle', category: 'Trucks',
    title: 'Mack Granite 2024 — New',
    description: 'The 2024 Mack Granite is a brand-new heavy-duty dump truck built for construction and aggregate hauling. A Mack MP8 12.8L diesel delivers 505 horsepower through a Mack mDRIVE 12-speed automated manual and 6x4 drivetrain. The Hardox steel dump body, hydraulic hoist, and 33,000 lb GVWR payload make it the benchmark for quarry and road construction work. Stock #STK-T0023.',
    price: 132000, currency: 'USD',
    brand: 'Mack', model: 'Granite', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: 'Mack mDRIVE 12-Speed', fuel_type: 'Diesel',
    engine: 'Mack MP8 12.8L I6 (505 HP)',
    drive_type: '6x4', color: 'Orange',
    payload_capacity: '33,000 lbs GVWR', towing_capacity: 'N/A',
    vin: 'MA202400023', stock_number: 'STK-T0023',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.mackGranite),
    rating: 4.7, rating_count: 19, favorite_count: 14,
    features: ['Hardox Steel Bed', 'Hydraulic Hoist', 'Tarp System', 'Mack mDRIVE', 'Heated Mirrors', 'Backup Camera', 'Air Suspension Seat', 'LED Work Lights'],
  },
  {
    property_id: 'KCO-T0024', listing_type: 'vehicle', category: 'Trucks',
    title: 'International 4300 Wrecker 2025 — New',
    description: 'The 2025 International 4300 Wrecker is a brand-new tow truck configured for recovery and roadside service. A Navistar N7 6.7L diesel produces 350 horsepower through an Allison 6-speed automatic and 2WD drivetrain. The wrecker body features a hydraulic boom, wheel lift, and under-lift recovery system with a 25,999 lb GVWR rating. Stock #STK-T0024.',
    price: 78500, currency: 'USD',
    brand: 'International', model: '4300 Wrecker', model_year: 2025,
    condition: 'New', mileage: '0 mi',
    transmission: 'Allison 6-Speed Auto', fuel_type: 'Diesel',
    engine: 'Navistar N7 6.7L I6 (350 HP)',
    drive_type: '2WD', color: 'Yellow',
    payload_capacity: '25,999 lbs GVWR', towing_capacity: 'N/A',
    vin: 'IN202500024', stock_number: 'STK-T0024',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.intlWrecker),
    rating: 4.5, rating_count: 24, favorite_count: 17,
    features: ['Wheel Lift', 'Hydraulic Boom', 'Under-Lift', 'Winch', 'LED Light Bar', 'Strobe Lights', 'Toolbox Storage', 'Remote Control'],
  },
  {
    property_id: 'KCO-T0025', listing_type: 'vehicle', category: 'Trucks',
    title: 'Kenworth T880 Tanker 2024 — New',
    description: 'The 2024 Kenworth T880 Tanker is a brand-new heavy-duty tanker for fuel and liquid transport. A PACCAR MX-13 diesel produces 500 horsepower through an Eaton 13-speed manual and 6x4 drivetrain. The aluminum tank body with pump, vapor recovery, and bottom loading supports a 33,000 lb GVWR payload for safe petroleum transfer. Stock #STK-T0025.',
    price: 139000, currency: 'USD',
    brand: 'Kenworth', model: 'T880 Tanker', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: 'Eaton 13-Speed Manual', fuel_type: 'Diesel',
    engine: 'PACCAR MX-13 12.9L I6 (500 HP)',
    drive_type: '6x4', color: 'Silver',
    payload_capacity: '33,000 lbs GVWR', towing_capacity: 'N/A',
    vin: 'KE202400025', stock_number: 'STK-T0025',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.t880Tanker),
    rating: 4.8, rating_count: 21, favorite_count: 16,
    features: ['Aluminum Tank', 'Pump System', 'Vapor Recovery', 'Bottom Loading', 'Manhole Covers', 'Rollover Protection', 'ABS', 'LED Lighting'],
  },
  {
    property_id: 'KCO-T0026', listing_type: 'vehicle', category: 'Trucks',
    title: 'Freightliner M2 Reefer 2024 — New',
    description: 'The 2024 Freightliner M2 Reefer is a brand-new refrigerated truck for temperature-controlled freight. A Cummins B6.7 diesel produces 360 horsepower through an Allison 6-speed automatic and 2WD drivetrain. The Carrier reefer unit, insulated box, and telematics keep perishables at precise temperatures within a 26,000 lb GVWR payload. Stock #STK-T0026.',
    price: 76500, currency: 'USD',
    brand: 'Freightliner', model: 'M2 Reefer', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: 'Allison 6-Speed Auto', fuel_type: 'Diesel',
    engine: 'Cummins B6.7 6.7L I6 (360 HP)',
    drive_type: '2WD', color: 'White',
    payload_capacity: '26,000 lbs GVWR', towing_capacity: 'N/A',
    vin: 'FR202400026', stock_number: 'STK-T0026',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.m2Reefer),
    rating: 4.5, rating_count: 18, favorite_count: 12,
    features: ['Carrier Reefer Unit', 'Insulated Box', 'Temperature Control', 'Telematics', 'Rear Door Seal', 'Backup Camera', 'LED Box Lighting', 'Fuel-Efficient Cooling'],
  },
  {
    property_id: 'KCO-T0027', listing_type: 'vehicle', category: 'Trucks',
    title: 'Freightliner M2 Box 2023 — Used',
    description: 'The 2023 Freightliner M2 Box is a well-maintained used delivery truck ready for city routes. A Cummins B6.7 diesel produces 300 horsepower through an Allison 6-speed automatic and 2WD drivetrain. The 26-foot dry box with swing doors and a 25,995 lb GVWR offer ample cargo volume; 67,400 miles with service records. Stock #STK-T0027.',
    price: 52000, currency: 'USD',
    brand: 'Freightliner', model: 'M2 Box', model_year: 2023,
    condition: 'Used', mileage: '67,400 mi',
    transmission: 'Allison 6-Speed Auto', fuel_type: 'Diesel',
    engine: 'Cummins B6.7 6.7L I6 (300 HP)',
    drive_type: '2WD', color: 'White',
    payload_capacity: '25,995 lbs GVWR', towing_capacity: 'N/A',
    vin: 'FR202300027', stock_number: 'STK-T0027',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.m2Box),
    rating: 4.4, rating_count: 16, favorite_count: 11,
    features: ['26-Foot Box', 'Swing Rear Doors', 'E-Track', 'Roll-Up Door', 'Backup Camera', 'Side Mirrors with Heaters', 'LED Interior', 'Service Records'],
  },
  {
    property_id: 'KCO-T0028', listing_type: 'vehicle', category: 'Trucks',
    title: 'Isuzu NQR 2024 — New',
    description: 'The 2024 Isuzu NQR is a brand-new box truck for urban delivery and commercial fleets. A 5.2L turbo-diesel four-cylinder produces 215 horsepower through a 6-speed automatic and 2WD drivetrain. The 16-foot box, roll-up rear door, and 12,000 lb GVWR payload deliver reliable, fuel-efficient cargo service. Stock #STK-T0028.',
    price: 56500, currency: 'USD',
    brand: 'Isuzu', model: 'NQR', model_year: 2024,
    condition: 'New', mileage: '0 mi',
    transmission: '6-Speed Auto', fuel_type: 'Diesel',
    engine: '5.2L I4 Diesel (215 HP)',
    drive_type: '2WD', color: 'White',
    payload_capacity: '12,000 lbs GVWR', towing_capacity: 'N/A',
    vin: 'IS202400028', stock_number: 'STK-T0028',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.isuzuNqr),
    rating: 4.6, rating_count: 35, favorite_count: 22,
    features: ['16-Foot Box', 'Roll-Up Rear Door', 'E-Track System', 'Power Liftgate', 'Backup Camera', 'Air Suspension', 'Keyless Entry', 'LED Lighting'],
  },
  {
    property_id: 'KCO-T0029', listing_type: 'vehicle', category: 'Trucks',
    title: 'Hino 268 2023 — Used',
    description: 'The 2023 Hino 268 is a well-maintained used Class 6 box truck with legendary Japanese reliability. A 6.7L J08E turbo-diesel produces 260 horsepower through an Allison 6-speed automatic and 2WD drivetrain. The 24-foot box, 25,950 lb GVWR, and 58,900 miles make it a proven workhorse for fleets and moving companies. Stock #STK-T0029.',
    price: 48000, currency: 'USD',
    brand: 'Hino', model: '268', model_year: 2023,
    condition: 'Used', mileage: '58,900 mi',
    transmission: 'Allison 6-Speed Auto', fuel_type: 'Diesel',
    engine: 'Hino J08E 6.7L I6 (260 HP)',
    drive_type: '2WD', color: 'White',
    payload_capacity: '25,950 lbs GVWR', towing_capacity: 'N/A',
    vin: 'HI202300029', stock_number: 'STK-T0029',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.hino268),
    rating: 4.5, rating_count: 23, favorite_count: 15,
    features: ['24-Foot Box', 'Allison Auto', 'J08E Diesel', 'Roll-Up Door', 'Backup Camera', 'Air Brakes', 'Cruise Control', 'Service History'],
  },
  {
    property_id: 'KCO-T0030', listing_type: 'vehicle', category: 'Trucks',
    title: 'Ford F-750 Dump 2019 — Used',
    description: 'The 2019 Ford F-750 is a rugged used dump truck built for heavy municipal and contractor work. A 6.7L Power Stroke diesel produces 330 horsepower through an Allison 6-speed automatic and 4WD drivetrain. The steel dump bed with hydraulic hoist supports a 33,000 lb GVWR payload; 96,500 miles with a clean maintenance file. Stock #STK-T0030.',
    price: 85000, currency: 'USD',
    brand: 'Ford', model: 'F-750 Dump', model_year: 2019,
    condition: 'Used', mileage: '96,500 mi',
    transmission: 'Allison 6-Speed Auto', fuel_type: 'Diesel',
    engine: '6.7L Power Stroke V8 (330 HP)',
    drive_type: '4WD', color: 'White',
    payload_capacity: '33,000 lbs GVWR', towing_capacity: 'N/A',
    vin: 'FO201900030', stock_number: 'STK-T0030',
    listing_status: 'sale',
    images: buildGallery(TRUCK_GALLERIES.f750Dump),
    rating: 4.6, rating_count: 27, favorite_count: 18,
    features: ['Steel Dump Bed', 'Hydraulic Hoist', '4WD', 'Power Stroke Diesel', 'Pintle Hitch', 'Heated Mirrors', 'Backup Camera', 'Maintenance Records'],
  },
];

export function formatTruckPrice(listing) {
  return listing.price.toLocaleString('en-US', { style: 'currency', currency: listing.currency || 'USD', maximumFractionDigits: 0 });
}

const TRUCK_MAP = new Map(TRUCK_LISTINGS.map(t => [t.property_id, t]));
export function getTruckById(id) { return TRUCK_MAP.get(id); }
