/*
# Create First Administrator Account

## Purpose
Creates the first super administrator account for KCO Global Online Marketplace.
This is a one-time bootstrap migration that:
1. Creates the admin user in auth.users with a secure temporary password.
2. Creates their profile with is_admin = true.
3. Assigns super_admin role in admin_roles.
4. Locks down the is_admin column so it can ONLY be modified by the service role
   (preventing any client-side self-promotion to admin).

## New Data
- auth.users row: admin@kcoglobalonlinemarket.com
- profiles row: is_admin = true for the admin user
- admin_roles row: role = 'super_admin' with full permissions

## Security Changes
- Revoke UPDATE on profiles.is_admin from the authenticated role so no client
  can ever set is_admin = true on their own profile.
- The is_admin flag can only be changed via the service role key (server-side).
- Public customer registration remains unaffected — new profiles default to
  is_admin = false and cannot be changed from the client.

## Important Notes
1. The temporary password is "KCO-Admin-2026!Secure" — the admin must change
   it immediately after first login.
2. Email confirmation is disabled for this account (admin can log in right away).
3. Only the service role can grant/revoke admin status going forward.
*/

-- ── 1. Create the admin user in auth.users ─────────────────────
-- Use a DO block to avoid errors if the user somehow already exists.
DO $$
DECLARE
  admin_id uuid;
  admin_email text := 'admin@kcoglobalonlinemarket.com';
  admin_password text := 'KCO-Admin-2026!Secure';
BEGIN
  -- Check if user already exists
  SELECT id INTO admin_id FROM auth.users WHERE email = admin_email;

  IF admin_id IS NULL THEN
    -- Create the admin user with a temporary password
    -- encrypted password is auto-generated by auth.users
    INSERT INTO auth.users (
      instance_id,
      id,
      aud,
      role,
      email,
      encrypted_password,
      email_confirmed_at,
      created_at,
      updated_at,
      raw_app_meta_data,
      raw_user_meta_data
    ) VALUES (
      '00000000-0000-0000-0000-000000000000',
      gen_random_uuid(),
      'authenticated',
      'authenticated',
      admin_email,
      extensions.crypt(admin_password, extensions.gen_salt('bf')),
      now(),
      now(),
      now(),
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"display_name":"KCO Administrator"}'::jsonb
    )
    RETURNING id INTO admin_id;
  END IF;

  -- ── 2. Create or update the admin profile ───────────────────
  INSERT INTO public.profiles (user_id, is_admin, display_name, country_code)
  VALUES (admin_id, true, 'KCO Administrator', 'US')
  ON CONFLICT (user_id) DO UPDATE
  SET is_admin = true,
      display_name = 'KCO Administrator';

  -- ── 3. Assign super_admin role ───────────────────────────────
  INSERT INTO public.admin_roles (user_id, role, permissions)
  VALUES (
    admin_id,
    'super_admin',
    '["dashboard","products","orders","special-orders","customers","payments","shipping","promotions","content","email","analytics","ai","security","settings","ai-settings","integrations"]'::jsonb
  )
  ON CONFLICT DO NOTHING;

END $$;

-- ── 4. Lock down profiles.is_admin ────────────────────────────
-- Revoke the ability for any client (authenticated or anon) to UPDATE
-- the is_admin column. Only the service role (which bypasses RLS) can
-- change admin status going forward.
-- We do this by creating a trigger that prevents client updates to is_admin
-- unless the current role is service_role.

CREATE OR REPLACE FUNCTION public.protect_is_admin()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Allow service_role to modify is_admin (service role bypasses RLS)
  -- Block any attempt by authenticated/anon to change is_admin
  IF current_setting('role', true) = 'authenticated' OR current_setting('role', true) = 'anon' THEN
    -- Only block if the is_admin value is actually being changed to true
    IF NEW.is_admin = true AND (OLD IS NULL OR OLD.is_admin = false) THEN
      RAISE EXCEPTION 'Permission denied: you cannot grant yourself admin privileges.';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_is_admin ON public.profiles;
CREATE TRIGGER trg_protect_is_admin
  BEFORE INSERT OR UPDATE OF is_admin ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_is_admin();

-- ── 5. Update is_current_user_admin to also check admin_roles ──
-- This makes the admin check more robust by checking both profiles.is_admin
-- and the admin_roles table.
CREATE OR REPLACE FUNCTION public.is_current_user_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT COALESCE(
    (SELECT is_admin FROM public.profiles WHERE user_id = auth.uid()),
    false
  ) OR EXISTS (
    SELECT 1 FROM public.admin_roles WHERE user_id = auth.uid()
  );
$$;
